// ===== 지역 설정 (17개 시·도) =====
const REGIONS = {
  seoul: {
    id: 'seoul',
    name: '서울특별시',
    shortName: '서울',
    description: '근현대 문학의 중심지. 수많은 시인과 소설가들이 이곳에서 작품 활동을 했다.',
    coords: { lat: 37.5665, lng: 126.9780 }
  },
  gyeonggi: {
    id: 'gyeonggi',
    name: '경기도',
    shortName: '경기',
    description: '수도를 둘러싼 넓은 들녘. 소나기가 내리던 양평, 실학의 고장 수원.',
    coords: { lat: 37.4138, lng: 127.5183 }
  },
  incheon: {
    id: 'incheon',
    name: '인천광역시',
    shortName: '인천',
    description: '바다와 하늘을 잇는 관문. 개항의 역사가 서린 항구 도시.',
    coords: { lat: 37.4563, lng: 126.7052 }
  },
  gangwon: {
    id: 'gangwon',
    name: '강원특별자치도',
    shortName: '강원',
    description: '산과 자연이 빚어낸 서정의 고장. 메밀꽃과 동백꽃의 무대.',
    coords: { lat: 37.8228, lng: 128.1555 }
  },
  chungbuk: {
    id: 'chungbuk',
    name: '충청북도',
    shortName: '충북',
    description: '내륙의 고요한 문학 정원. 정지용의 향수가 시작된 곳.',
    coords: { lat: 36.6357, lng: 127.4912 }
  },
  sejong: {
    id: 'sejong',
    name: '세종특별자치시',
    shortName: '세종',
    description: '새로운 행정수도. 금강이 흐르는 미래의 도시.',
    coords: { lat: 36.4800, lng: 127.0000 }
  },
  chungnam: {
    id: 'chungnam',
    name: '충청남도',
    shortName: '충남',
    description: '충절과 낭만이 흐르는 문학의 터전.',
    coords: { lat: 36.5184, lng: 126.8000 }
  },
  daejeon: {
    id: 'daejeon',
    name: '대전광역시',
    shortName: '대전',
    description: '과학과 교통의 도시. 한밭에서 피어나는 문화.',
    coords: { lat: 36.3504, lng: 127.3845 }
  },
  gyeongbuk: {
    id: 'gyeongbuk',
    name: '경상북도',
    shortName: '경북',
    description: '천년 고도의 이야기. 신라의 땅에서 피어난 문학.',
    coords: { lat: 36.4919, lng: 128.8889 }
  },
  daegu: {
    id: 'daegu',
    name: '대구광역시',
    shortName: '대구',
    description: '분지의 뜨거운 열정. 저항 문학과 근대의 기억.',
    coords: { lat: 35.8714, lng: 128.6014 }
  },
  jeonbuk: {
    id: 'jeonbuk',
    name: '전북특별자치도',
    shortName: '전북',
    description: '판소리와 한의 문학이 살아 숨 쉬는 곳.',
    coords: { lat: 35.7175, lng: 127.1530 }
  },
  gwangju: {
    id: 'gwangju',
    name: '광주광역시',
    shortName: '광주',
    description: '민주와 예술의 도시. 5월의 기억을 품은 문학의 성지.',
    coords: { lat: 35.1595, lng: 126.8526 }
  },
  jeonnam: {
    id: 'jeonnam',
    name: '전라남도',
    shortName: '전남',
    description: '남도의 정서와 역사가 깃든 문학의 고향.',
    coords: { lat: 34.8679, lng: 126.9910 }
  },
  ulsan: {
    id: 'ulsan',
    name: '울산광역시',
    shortName: '울산',
    description: '고래와 바다의 도시. 처용의 전설이 살아 있는 곳.',
    coords: { lat: 35.5384, lng: 129.3114 }
  },
  gyeongnam: {
    id: 'gyeongnam',
    name: '경상남도',
    shortName: '경남',
    description: '바다와 강이 만나는 곳, 대하소설의 무대.',
    coords: { lat: 35.4606, lng: 128.2132 }
  },
  busan: {
    id: 'busan',
    name: '부산광역시',
    shortName: '부산',
    description: '피란의 기억과 바다의 낭만이 공존하는 항구 도시.',
    coords: { lat: 35.1796, lng: 129.0756 }
  },
  jeju: {
    id: 'jeju',
    name: '제주특별자치도',
    shortName: '제주',
    description: '바람과 돌과 바다의 섬. 아픈 역사를 품은 문학의 섬.',
    coords: { lat: 33.4890, lng: 126.4983 }
  },

  // ===== 세분화 지역 (시·군 — 파일럿) =====
  chuncheon: {
    id: 'chuncheon',
    name: '춘천',
    shortName: '춘천',
    parentRegion: 'gangwon',
    description: '김유정의 고향. 실레마을에 김유정문학촌이 있는 한국 단편소설의 성지.',
    coords: { lat: 37.8813, lng: 127.7298 }
  },
  bongpyeong: {
    id: 'bongpyeong',
    name: '봉평 (평창)',
    shortName: '봉평',
    parentRegion: 'gangwon',
    description: '이효석의 메밀꽃 필 무렵의 무대. 봉평장과 메밀꽃 축제로 유명.',
    coords: { lat: 37.6003, lng: 128.3968 }
  },
  gyeongju: {
    id: 'gyeongju',
    name: '경주',
    shortName: '경주',
    parentRegion: 'gyeongbuk',
    description: '천년 고도 신라의 수도. 박목월, 김동리의 문학적 고향.',
    coords: { lat: 35.8562, lng: 129.2247 }
  },
  gunsan: {
    id: 'gunsan',
    name: '군산',
    shortName: '군산',
    parentRegion: 'jeonbuk',
    description: '금강 하구의 항구 도시. 채만식 탁류의 배경이 된 근대 역사의 현장.',
    coords: { lat: 35.9676, lng: 126.7369 }
  },
  hadong: {
    id: 'hadong',
    name: '하동',
    shortName: '하동',
    parentRegion: 'gyeongnam',
    description: '섬진강과 지리산이 만나는 곳. 박경리 토지의 무대 악양면이 있다.',
    coords: { lat: 35.0676, lng: 127.7513 }
  },
  tongyeong: {
    id: 'tongyeong',
    name: '통영',
    shortName: '통영',
    parentRegion: 'gyeongnam',
    description: '남해의 보석 같은 항구. 유치환, 김춘수 등 한국 시문학의 요람.',
    coords: { lat: 34.8544, lng: 128.4333 }
  },
  gangneung: {
    id: 'gangneung',
    name: '강릉',
    shortName: '강릉',
    parentRegion: 'gangwon',
    description: '관동별곡의 무대. 경포대와 허난설헌 생가가 있는 동해안 문학의 거점.',
    coords: { lat: 37.7519, lng: 128.8761 }
  },
  yangpyeong: {
    id: 'yangpyeong',
    name: '양평',
    shortName: '양평',
    parentRegion: 'gyeonggi',
    description: '소나기의 배경. 황순원문학촌 소나기마을이 있는 서정의 고장.',
    coords: { lat: 37.4917, lng: 127.4875 }
  },
  okcheon: {
    id: 'okcheon',
    name: '옥천',
    shortName: '옥천',
    parentRegion: 'chungbuk',
    description: '정지용의 고향. 향수의 넓은 벌과 실개천의 원풍경.',
    coords: { lat: 36.3067, lng: 127.5706 }
  },
  buyeo: {
    id: 'buyeo',
    name: '부여',
    shortName: '부여',
    parentRegion: 'chungnam',
    description: '백제의 마지막 수도. 신동엽의 역사 의식이 길러진 고도.',
    coords: { lat: 36.2756, lng: 126.9098 }
  },
  andong: {
    id: 'andong',
    name: '안동',
    shortName: '안동',
    parentRegion: 'gyeongbuk',
    description: '유교 문화의 본향. 이육사의 저항 정신이 태어난 땅.',
    coords: { lat: 36.5684, lng: 128.7294 }
  },
  namwon: {
    id: 'namwon',
    name: '남원',
    shortName: '남원',
    parentRegion: 'jeonbuk',
    description: '춘향전과 혼불의 무대. 한국 서사문학의 성지.',
    coords: { lat: 35.4164, lng: 127.3907 }
  },
  gochang: {
    id: 'gochang',
    name: '고창',
    shortName: '고창',
    parentRegion: 'jeonbuk',
    description: '미당 서정주의 고향. 선운사와 국화밭이 어우러진 시의 고장.',
    coords: { lat: 35.4356, lng: 126.7020 }
  },
  beolgyo: {
    id: 'beolgyo',
    name: '벌교',
    shortName: '벌교',
    parentRegion: 'jeonnam',
    description: '태백산맥의 중심 무대. 소화다리와 읍내에 소설의 흔적이 남아 있다.',
    coords: { lat: 34.8422, lng: 127.3388 }
  },
  mokpo: {
    id: 'mokpo',
    name: '목포',
    shortName: '목포',
    parentRegion: 'jeonnam',
    description: '한국 최초 여성 소설가 박화성의 고향. 개항과 근대의 기억이 서린 항구 도시.',
    coords: { lat: 34.8118, lng: 126.3922 }
  },

  // ===== 세분화 지역 추가 =====
  sokcho: {
    id: 'sokcho',
    name: '속초',
    shortName: '속초',
    parentRegion: 'gangwon',
    description: '설악산과 동해가 만나는 곳. 이순원의 문학적 고향.',
    coords: { lat: 38.2070, lng: 128.5918 }
  },
  yeongyang: {
    id: 'yeongyang',
    name: '영양',
    shortName: '영양',
    parentRegion: 'gyeongbuk',
    description: '조지훈과 이문열의 고향. 주실마을과 두들마을이 있는 문학의 오지.',
    coords: { lat: 36.6667, lng: 129.1122 }
  },
  jeonju: {
    id: 'jeonju',
    name: '전주',
    shortName: '전주',
    parentRegion: 'jeonbuk',
    description: '한옥마을과 판소리의 고장. 전통 문화와 문학이 살아 숨 쉬는 곳.',
    coords: { lat: 35.8242, lng: 127.1480 }
  },
  namhae: {
    id: 'namhae',
    name: '남해',
    shortName: '남해',
    parentRegion: 'gyeongnam',
    description: '김만중 유배지. 바다와 산이 어우러진 남쪽 끝 섬.',
    coords: { lat: 34.8377, lng: 127.8925 }
  },
  haenam: {
    id: 'haenam',
    name: '해남',
    shortName: '해남',
    parentRegion: 'jeonnam',
    description: '윤선도의 보길도와 땅끝마을. 한반도 최남단의 문학 고장.',
    coords: { lat: 34.5736, lng: 126.5993 }
  },
  gangjin: {
    id: 'gangjin',
    name: '강진',
    shortName: '강진',
    parentRegion: 'jeonnam',
    description: '김영랑의 고향이자 정약용의 유배지. 시와 실학이 꽃핀 남도의 문학 성지.',
    coords: { lat: 34.6419, lng: 126.7670 }
  },
  damyang: {
    id: 'damyang',
    name: '담양',
    shortName: '담양',
    parentRegion: 'jeonnam',
    description: '가사문학의 산실. 식영정과 면앙정에서 조선 시가문학의 절정이 피어났다.',
    coords: { lat: 35.3213, lng: 126.9882 }
  }
};

// ===== 문학 작품 데이터 =====
const LITERARY_DATA = [
  // ── 서울 ──
  {
    id: 'lit-1',
    region: 'seoul',
    title: '서시',
    author: '윤동주',
    year: 1941,
    genre: '시',
    location: '서울 연희동 연세대학교',
    excerpt: '죽는 날까지 하늘을 우러러\n한 점 부끄럼이 없기를,\n잎새에 이는 바람에도\n나는 괴로워했다.',
    description: '식민지 시대 지식인의 양심과 자기 성찰을 노래한 대표작. 윤동주가 연희전문학교 재학 시절 이곳에서 썼다. 연세대학교 캠퍼스에 윤동주 시비와 기념관이 있다.',
    mood: ['성찰', '고독'],
    coords: { lat: 37.5654, lng: 126.9372 },
    district: '연희동'
  },
  {
    id: 'lit-2',
    region: 'seoul',
    title: '날개',
    author: '이상',
    year: 1936,
    genre: '소설',
    location: '서울 종로 미쓰코시 옥상',
    excerpt: '박제가 되어 버린 천재를 아시오?',
    description: '근대 지식인의 무기력과 자의식 붕괴를 그린 심리 소설. 종로의 골목과 미쓰코시 백화점 옥상이 주요 무대이다. 미쓰코시 자리에 현재 신세계백화점 본점이 있다.',
    mood: ['고독', '성찰'],
    coords: { lat: 37.5610, lng: 126.9812 },
    district: '종로'
  },
  {
    id: 'lit-3',
    region: 'seoul',
    title: '서울, 1964년 겨울',
    author: '김승옥',
    year: 1965,
    genre: '소설',
    location: '서울 종로',
    excerpt: '나는 한 사나이를 알고 있다.\n그 사나이와 더불어 겨울 한때를 지냈건마는 어찌 된 셈인지 지금은 그의 이름조차 기억할 수 없다.',
    description: '산업화 시대 서울의 소외와 고독을 감각적 문체로 그린 모더니즘 소설의 대표작. 1960년대 겨울밤 종로 일대가 배경이다.',
    mood: ['고독'],
    coords: { lat: 37.5709, lng: 126.9997 },
    district: '종로'
  },
  {
    id: 'lit-32',
    region: 'seoul',
    title: '삼대',
    author: '염상섭',
    year: 1931,
    genre: '소설',
    location: '서울 안국동 일대',
    excerpt: '조의관은 수염을 쓸어 내리며 혼자 한숨을 쉬었다. 집안이 어찌 되려고 이러는고 싶었다.',
    description: '일제강점기 서울 중산층 가문의 삼대에 걸친 몰락을 사실주의적으로 그린 한국 근대 장편소설의 대표작. 안국동과 종로 일대가 조씨 집안의 생활 무대이다. 인근 국립한국문학관에서 염상섭 관련 자료를 볼 수 있다.',
    mood: ['사실', '세태'],
    coords: { lat: 37.5784, lng: 126.9850 },
    district: '종로'
  },
  {
    id: 'lit-33',
    region: 'seoul',
    title: '천변풍경',
    author: '박태원',
    year: 1936,
    genre: '소설',
    location: '서울 청계천 광교 일대',
    excerpt: '빨래터에서 아낙네들이 저마끔 남편의 흉을 보고, 시어미의 흉을 보고, 또 동네 사람의 흉을 보며 빨래를 하고 있었다.',
    description: '청계천변 서민 삼십여 명의 일상을 카메라처럼 포착한 세태 소설의 걸작. 광교와 수표교 사이 청계천 빨래터가 이야기의 중심 무대이다. 청계천박물관에서 소설 속 천변 풍경 자료를 볼 수 있다.',
    mood: ['일상', '서민'],
    coords: { lat: 37.5694, lng: 126.9862 },
    district: '종로'
  },
  {
    id: 'lit-34',
    region: 'seoul',
    title: '소설가 구보씨의 일일',
    author: '박태원',
    year: 1934,
    genre: '소설',
    location: '서울 종로 화신백화점 일대',
    excerpt: '어머니는 아들이 제 방에서 나와, 마루 끝에 놓인 구두를 신고, 기둥 못에 걸린 단장을 떼어 들고, 그리고 문간으로 향하여 나가는 소리를 들었다.',
    description: '무직 소설가 구보가 하루 동안 경성 거리를 배회하며 현대인의 고독과 권태를 기록한 모더니즘 소설. 종로 화신백화점, 광교, 경성역 등 1930년대 서울 도심이 산책 경로이다.',
    mood: ['고독', '도시'],
    coords: { lat: 37.5700, lng: 126.9850 },
    district: '종로'
  },
  {
    id: 'lit-35',
    region: 'seoul',
    title: '운수 좋은 날',
    author: '현진건',
    year: 1924,
    genre: '소설',
    location: '서울 동소문 일대',
    excerpt: '새침하게 흐린 품이 눈이 올 듯하더니 눈은 아니 오고 얼다가 만 비가 추적추적 내리었다.',
    description: '인력거꾼 김첨지의 하루를 통해 식민지 하층민의 비참한 삶을 반어적으로 그린 사실주의 단편의 걸작. 동소문에서 남대문정거장까지 경성 거리가 배경이다. 혜화동 일대에서 소설 속 동소문 밖 풍경을 느낄 수 있다.',
    mood: ['비극', '서민'],
    coords: { lat: 37.5872, lng: 127.0017 },
    district: '종로'
  },
  {
    id: 'lit-36',
    region: 'seoul',
    title: '무정',
    author: '이광수',
    year: 1917,
    genre: '소설',
    location: '서울 남대문역 일대',
    excerpt: '경성 학교 영어 교사 이형식은 오후 두시 사년급 영어 시간을 마치고 내려쪼이는 유월 볕에 땀을 흘리면서 안동 김장로의 집으로 간다.',
    description: '한국 최초의 근대 장편소설로, 구시대와 신시대 사이에서 갈등하는 청년 지식인의 사랑과 계몽 의식을 그렸다. 소설 후반부에서 주인공 일행이 남대문 정거장에서 기차를 타고 부산으로 향하는 장면이 전환점이 된다. 남대문역 자리에 현재 문화역서울284(구 서울역사)가 남아 있다.',
    mood: ['계몽', '성찰'],
    coords: { lat: 37.5532, lng: 126.9726 },
    district: '중구'
  },
  {
    id: 'lit-37',
    region: 'seoul',
    title: '나목',
    author: '박완서',
    year: 1970,
    genre: '소설',
    location: '서울 명동 미군 PX',
    excerpt: '여인들의 눈앞엔 겨울이 있고, 나목에겐 아직 멀지만 봄에의 믿음이 있다.',
    description: '한국전쟁 직후 서울을 배경으로, 미군 PX 초상화부에서 일하는 여성의 눈을 통해 전쟁과 예술과 삶의 의미를 탐색한 박완서의 등단작이다. 명동의 미군 PX 초상화 가게가 주 무대이며, 가난한 화가 옥희도는 실존 화가 박수근을 모델로 했다. 명동 일대에서 당시 전후 문화의 흔적을 더듬어 볼 수 있다.',
    mood: ['전쟁', '희망'],
    coords: { lat: 37.5636, lng: 126.9856 },
    district: '명동'
  },
  {
    id: 'lit-38',
    region: 'seoul',
    title: '달밤',
    author: '이태준',
    year: 1933,
    genre: '소설',
    location: '서울 성북동',
    excerpt: '성북동으로 이사 나와서 한 대엿새 되었을까, 그날 밤 나는 보던 신문을 머리맡에 밀어 던지고 누워 새삼스럽게, \'여기도 정말 시골이로군!\' 하였다.',
    description: '도시 변두리 성북동에서 만난 순박한 인물 황수건을 통해 근대화 속 소외된 삶을 서정적으로 그린 단편이다. 작가 이태준이 실제 살았던 성북동이 작품의 배경이자 서사의 출발점이다. 이태준의 옛집인 수연산방이 전통 찻집으로 운영되며 문학 탐방지로 남아 있다.',
    mood: ['서정', '향수'],
    coords: { lat: 37.5950, lng: 126.9948 },
    district: '성북동'
  },
  {
    id: 'lit-39',
    region: 'seoul',
    title: '님의 침묵',
    author: '한용운',
    year: 1926,
    genre: '시',
    location: '서울 성북동 심우장',
    excerpt: '님은 갔습니다. 아아, 사랑하는 나의 님은 갔습니다.\n푸른 산빛을 깨치고, 단풍나무 숲을 향하야 난 적은 길을 걸어서, 차마 떨치고 갔습니다.',
    description: '일제강점기 빼앗긴 조국과 님에 대한 영원한 사랑과 기다림을 노래한 한용운의 대표 시집 표제작. 한용운이 1933년부터 1944년 입적할 때까지 만년을 보낸 성북동 심우장에서 독립을 향한 의지를 지켰다. 심우장은 사적 제550호로 지정되어 현재도 방문할 수 있다.',
    mood: ['그리움', '의지'],
    coords: { lat: 37.5936, lng: 126.9917 },
    district: '성북동'
  },
  {
    id: 'lit-40',
    region: 'seoul',
    title: '풀',
    author: '김수영',
    year: 1968,
    genre: '시',
    location: '서울 도봉구 방학동',
    excerpt: '풀이 눕는다\n비를 몰아오는 동풍에 나부껴\n풀은 눕고\n드디어 울었다',
    description: '바람에 눕지만 바람보다 먼저 일어나는 풀의 이미지로 민중의 저항과 생명력을 노래한 김수영의 유고작. 김수영이 도봉구 방학동에 거주하며 도봉산 자락의 자연 속에서 시작 활동을 이어간 곳이다. 도봉구 해등로32길에 김수영문학관이 있으며 시인의 유품과 자료를 전시하고 있다.',
    mood: ['저항', '생명'],
    coords: { lat: 37.6599, lng: 127.0238 },
    district: '방학동'
  },
  {
    id: 'lit-41',
    region: 'seoul',
    title: '오감도 시제1호',
    author: '이상',
    year: 1934,
    genre: '시',
    location: '서울 종로 제비다방 터',
    excerpt: '13인의아해가도로로질주하오.\n(길은막다른골목이적당하오.)\n제1의아해가무섭다고그리오.\n제2의아해도무섭다고그리오.',
    description: '근대 도시의 공포와 불안을 실험적 언어로 형상화한 한국 모더니즘 문학의 기념비적 연작시. 이상이 1933년 종로1가에 제비다방을 열고 문학 활동의 거점으로 삼았던 곳에서 발표되었다. 제비다방 터에는 현재 그랑서울 건물이 들어서 있으며, 종각역 인근에서 이상 문학 산책로를 걸을 수 있다.',
    mood: ['불안', '실험'],
    coords: { lat: 37.5707, lng: 126.9814 },
    district: '종로'
  },

  // ── 경기 ──
  {
    id: 'lit-25',
    region: 'yangpyeong',
    title: '소나기',
    author: '황순원',
    year: 1953,
    genre: '소설',
    location: '양평 서종면 소나기마을',
    excerpt: '소녀가 개울가에서 세수를 하고 있었다.',
    description: '소년과 소녀의 짧고 아름다운 만남을 그린 단편의 걸작. 양평의 들판과 개울이 작품의 서정적 배경이다. 양평군에 황순원문학촌 소나기마을이 있다.',
    mood: ['사랑', '서정'],
    coords: { lat: 37.5970, lng: 127.3780 },
    district: '서종면'
  },
  {
    id: 'lit-42',
    region: 'gyeonggi',
    title: '남한산성',
    author: '김훈',
    year: 2007,
    genre: '소설',
    location: '광주 남한산성',
    excerpt: '서울을 버려야 서울로 돌아올 수 있다는 말은 그럴듯하게 들렸다. 그해 겨울은 일찍 와서 오래 머물렀다.',
    description: '병자호란 당시 남한산성에 고립된 조정의 47일을 주화파와 척화파의 대립으로 그려낸 역사소설. 실제 병자호란의 항전지였던 남한산성이 소설의 전체 무대이며, 성곽 위의 추위와 굶주림이 문장 곳곳에 배어 있다. 남한산성은 유네스코 세계문화유산으로, 성곽 탐방로와 수어장대를 걸으며 소설 속 장면을 떠올릴 수 있다.',
    mood: ['비장', '역사'],
    coords: { lat: 37.4791, lng: 127.1802 },
    district: '남한산성면'
  },
  {
    id: 'lit-43',
    region: 'gyeonggi',
    title: '허생전',
    author: '박지원',
    year: 1780,
    genre: '소설',
    location: '안성 안성장터',
    excerpt: '허생은 묵적골에 살았다. 곧장 남산 밑에 닿으면, 우물 위에 오래 된 은행나무가 서 있고, 은행나무를 향하여 사립문이 열렸는데, 두어 칸 초가는 비바람을 막지 못할 정도였다.',
    description: '가난한 선비 허생이 만 냥을 빌려 안성 장터에서 매점매석으로 큰 이윤을 남기며 조선 사회의 모순을 풍자한 한문 단편소설. 허생이 처음 장사를 시작한 안성장은 조선 후기 전국 5대 장시의 하나로, 소설 속 상업 활동의 핵심 무대다. 안성맞춤박물관에서 조선 후기 장시 문화를 살펴볼 수 있다.',
    mood: ['풍자', '통쾌'],
    coords: { lat: 37.0108, lng: 127.2703 },
    district: '안성시'
  },
  {
    id: 'lit-44',
    region: 'gyeonggi',
    title: '난장이가 쏘아올린 작은 공',
    author: '조세희',
    year: 1978,
    genre: '소설',
    location: '성남 상대원동',
    excerpt: '사람들은 아버지를 난장이라고 불렀다. 사람들은 옳게 보았다. 아버지는 난장이였다. 불행하게도 사람들은 아버지를 보는 것 하나만 옳았다.',
    description: '1970년대 도시 재개발로 밀려난 철거민 가족의 비극을 연작 형식으로 그려낸 산업화 시대의 대표 소설. 광주대단지사건과 성남 상대원공단이 작품의 실제 배경이며, 소설 속 난장이네 가족이 쫓겨난 달동네의 원형이다. 성남시 수정구 일대에서 1970년대 서민 주거지의 흔적을 찾아볼 수 있다.',
    mood: ['비극', '저항'],
    coords: { lat: 37.4386, lng: 127.1578 },
    district: '상대원동'
  },
  {
    id: 'lit-45',
    region: 'gyeonggi',
    title: '보리타작',
    author: '정약용',
    year: 1801,
    genre: '시',
    location: '남양주 조안면 마재마을',
    excerpt: '밥 먹고는 도리깨 들고 타작마당 나가서니\n검게 탄 두 어깨가 햇볕 아래 번들번들\n호야호야 소리 내며 발 맞추어 두드리니\n금방사이 보리 이삭 질펀하게 널려 있다',
    description: '유배 직전의 정약용이 농민들의 보리타작 풍경을 생동감 넘치는 필치로 그려낸 한시. 정약용이 태어나고 학문을 닦은 남양주 마재마을이 시의 배경이며, 한강변 농촌의 풍경이 시 속에 살아 있다. 남양주시 조안면에 다산유적지가 조성되어 있으며, 생가 여유당과 기념관을 관람할 수 있다.',
    mood: ['서정', '전원'],
    coords: { lat: 37.5122, lng: 127.3308 },
    district: '조안면'
  },
  {
    id: 'lit-46',
    region: 'gyeonggi',
    title: '경희',
    author: '나혜석',
    year: 1918,
    genre: '소설',
    location: '수원 인계동 나혜석거리',
    excerpt: '경희도 사람이다. 그 다음에는 여자다. 그러면 여자라는 것보다 먼저 사람이다. 또 조선 사회의 여자보다 먼저 우주 안 전 인류의 여성이다.',
    description: '한국 최초의 여성 작가 나혜석이 여성도 사람이라는 선언을 담아낸 한국 근대 최초의 페미니즘 소설. 수원 출신인 나혜석의 고향에 나혜석거리가 조성되어 작가의 삶과 예술을 기리고 있다. 수원시 팔달구 인계동에 나혜석 동상과 나혜석거리가 있으며 약 600m의 문화예술 거리를 산책할 수 있다.',
    mood: ['각성', '선구'],
    coords: { lat: 37.2650, lng: 127.0020 },
    district: '인계동'
  },

  // ── 인천 ──
  {
    id: 'lit-47',
    region: 'incheon',
    title: '중국인 거리',
    author: '오정희',
    year: 1979,
    genre: '소설',
    location: '인천 중구 차이나타운',
    excerpt: '나는 깜깜하게 엎드린 바다를 보았다. 동지나 해로부터 밤새워 불어 오는 바람, 바람에 실린 해조류의 냄새를 깊이 들이마셨다.',
    description: '1950년대 말 인천 차이나타운을 배경으로 사춘기 소녀의 성장과 여성으로서의 자각을 섬세하게 그려낸 단편소설. 소설 속 중국인 거리의 이층집, 연안부두의 바닷바람, 양색시들의 골목이 모두 인천 중구 일대의 실제 풍경이다. 인천역 앞 차이나타운과 개항장 거리를 걸으며 소설 속 1950년대의 분위기를 떠올릴 수 있다.',
    mood: ['성장', '감각'],
    coords: { lat: 37.4745, lng: 126.6173 },
    district: '중구'
  },
  {
    id: 'lit-48',
    region: 'incheon',
    title: '괭이부리말 아이들',
    author: '김중미',
    year: 2000,
    genre: '소설',
    location: '인천 동구 만석동',
    excerpt: '아빠, 나 엄마 없어두 돼. 숙자가 아버지를 올려다보며 말했다.',
    description: '인천 만석동 빈민 마을 괭이부리말에서 가난과 결손 속에 살아가는 아이들의 삶을 사실적으로 그린 소설. 작가 김중미가 1987년부터 만석동에서 기차길옆공부방을 운영하며 직접 경험한 이야기가 바탕이다. 인천 동구 만석동 일대에서 소설의 배경이 된 골목과 기차길옆공부방 터를 찾아볼 수 있다.',
    mood: ['빈곤', '연대'],
    coords: { lat: 37.4735, lng: 126.6340 },
    district: '만석동'
  },
  {
    id: 'lit-49',
    region: 'incheon',
    title: '모든 경계에는 꽃이 핀다',
    author: '함민복',
    year: 1996,
    genre: '시',
    location: '강화 화도면 동막리',
    excerpt: '모든 경계에는 꽃이 핀다\n달빛과 그림자의 경계로 서서\n담장을 보았다\n집 안과 밖의 경계인 담장에\n화분이 있고\n꽃의 전생과 내생 사이에 국화가 피었다',
    description: '경계 위에 피어나는 꽃의 이미지로 분단과 삶의 안팎을 관조하는 함민복의 대표 시집 표제시. 시인이 1996년부터 강화도 동막리에 정착해 살며, 남북의 경계이자 바다와 갯벌의 경계인 강화도의 풍경을 시로 빚어냈다. 강화도 마니산과 동막해변 일대에서 시인이 살아온 강화의 자연을 만날 수 있다.',
    mood: ['관조', '경계'],
    coords: { lat: 37.5833, lng: 126.4500 },
    district: '화도면'
  },

  // ── 강원도 ──
  {
    id: 'lit-4',
    region: 'bongpyeong',
    title: '메밀꽃 필 무렵',
    author: '이효석',
    year: 1936,
    genre: '소설',
    location: '평창 봉평면 이효석문학관',
    excerpt: '산허리는 온통 메밀밭이어서 피기 시작한 꽃이 소금을 뿌린 듯이 흐붓한 달빛에 숨이 막힐 지경이다.',
    description: '장돌뱅이의 인생과 인연을 달빛 아래 서정적으로 그린 단편. 봉평 장터와 메밀밭 사이 달밤 길이 작품의 핵심 무대이다. 봉평에 이효석문학관이 있고 매년 메밀꽃 축제가 열린다.',
    mood: ['서정', '그리움'],
    coords: { lat: 37.6122, lng: 128.3683 },
    district: '봉평면'
  },
  {
    id: 'lit-5',
    region: 'chuncheon',
    title: '동백꽃',
    author: '김유정',
    year: 1936,
    genre: '소설',
    location: '춘천 실레마을',
    excerpt: '그리고 뒤에서 따라오던 점순이가 나의 등을 떠밀었다.\n나는 그대로 노란 동백꽃 속으로 폭 파묻혀 버렸다.',
    description: '시골 소년소녀의 순박한 사랑을 해학적으로 그린 단편. 춘천 실레마을의 산골 풍경이 작품의 배경이다. 실레마을에 김유정문학촌이 있다.',
    mood: ['사랑', '서정'],
    coords: { lat: 37.8190, lng: 127.7190 },
    district: '실레마을'
  },
  {
    id: 'lit-52',
    region: 'chuncheon',
    title: '봄봄',
    author: '김유정',
    year: 1935,
    genre: '소설',
    location: '춘천 실레마을 김유정문학촌',
    excerpt: '장인님! 인제 저……. 하고 입을 열려니까, 미리 알아채고 딴전을 부려 버린다.',
    description: '데릴사위의 서러움을 해학적으로 그린 희극적 단편의 걸작. 춘천 실레마을의 산골이 배경으로, 봉필이네 마름집과 감자밭의 풍경이 살아 있다. 실레마을 김유정문학촌에서 작품 속 마을을 거닐 수 있다.',
    mood: ['해학', '서정'],
    coords: { lat: 37.8190, lng: 127.7190 },
    district: '실레마을'
  },
  {
    id: 'lit-53',
    region: 'sokcho',
    title: '은비령',
    author: '이순원',
    year: 1996,
    genre: '소설',
    location: '속초 한계령 은비령 일대',
    excerpt: '왜 하필이면 길을 바꾸어 떠난 곳이 지도에도 나오지 않는 은비령이었을까.',
    description: '바다로 가는 길을 눈을 보러 가는 길로 바꾼 여행에서 시작되는 사랑 이야기. 한계령 꼭대기에서 동쪽 샛길로 빠지는 비밀스러운 고개가 소설의 무대이다. 한계령 정상 부근에서 소설 속 은비령의 정취를 느낄 수 있다.',
    mood: ['사랑', '서정'],
    coords: { lat: 38.1200, lng: 128.4650 },
    district: '한계령'
  },
  {
    id: 'lit-54',
    region: 'gangneung',
    title: '곡자',
    author: '허난설헌',
    year: 1580,
    genre: '시',
    location: '강릉 초당동 허난설헌 생가터',
    excerpt: '去年喪愛女 今年喪愛子\n哀哀廣陵土 雙墳相對起',
    description: '어린 딸과 아들을 연이어 잃은 어미의 처절한 슬픔을 노래한 한시. 강릉 초당동에서 태어난 허난설헌의 비극적 삶이 응축된 작품이다. 강릉 초당동에 허균허난설헌기념공원과 생가터가 있다.',
    mood: ['슬픔', '그리움'],
    coords: { lat: 37.7780, lng: 128.9050 },
    district: '초당동'
  },
  {
    id: 'lit-55',
    region: 'gangwon',
    title: '목마와 숙녀',
    author: '박인환',
    year: 1955,
    genre: '시',
    location: '인제 인제읍 박인환문학관',
    excerpt: '한 잔의 술을 마시고\n우리는 버지니아 울프의 생애와\n목마를 타고 떠난 숙녀의 옷자락을 이야기한다',
    description: '전후 세대의 허무와 낭만을 감각적으로 노래한 모더니즘 시의 대표작. 강원도 인제에서 태어난 시인이 서울 명동에서 문학적 감수성을 키웠다. 인제읍에 박인환문학관이 있다.',
    mood: ['허무', '낭만'],
    coords: { lat: 38.0690, lng: 128.1706 },
    district: '인제읍'
  },
  {
    id: 'lit-56',
    region: 'gangneung',
    title: '유대관령망친정',
    author: '신사임당',
    year: 1541,
    genre: '시',
    location: '강릉 대관령 고갯마루',
    excerpt: '慈親鶴髮在臨瀛\n身向長安獨去情\n回首北村時一望\n白雲飛下暮山靑',
    description: '대관령을 넘으며 강릉에 두고 온 어머니를 그리워한 칠언절구. 친정 강릉을 떠나 서울로 향하던 신사임당이 대관령 중턱에서 고향을 돌아보며 지은 시이다. 대관령 옛길에서 시 속 풍경을 만날 수 있다.',
    mood: ['그리움', '서정'],
    coords: { lat: 37.7310, lng: 128.8150 },
    district: '대관령'
  },
  {
    id: 'lit-57',
    region: 'gangwon',
    title: '헌화가',
    author: '작자 미상',
    year: 742,
    genre: '시',
    location: '삼척 원덕읍 수로부인헌화공원',
    excerpt: '자줏빛 바위 가에\n잡은 암소 놓게 하시고\n나를 아니 부끄러워하시면\n꽃을 꺾어 바치오리다',
    description: '신라 향가로, 수로부인의 아름다움에 반한 노인이 절벽 위 철쭉을 꺾어 바치며 부른 노래. 삼척 임원 해안의 절벽이 헌화가 설화의 배경지로 전해진다. 삼척 임원항에 수로부인헌화공원이 조성되어 있다.',
    mood: ['사랑', '서정'],
    coords: { lat: 37.2350, lng: 129.3420 },
    district: '원덕읍'
  },
  {
    id: 'lit-58',
    region: 'gangwon',
    title: '제왕운기',
    author: '이승휴',
    year: 1287,
    genre: '시',
    location: '삼척 미로면 두타산 천은사지',
    excerpt: '처음에 어느 누가 나라를 열었던고\n석제의 손자로 이름은 단군일세',
    description: '한국과 중국의 역사를 칠언시로 읊은 고려 시대 역사서. 이승휴가 삼척 두타산 천은사에서 10년간 머물며 집필했다. 삼척 미로면에 사적으로 지정된 이승휴 유적이 남아 있다.',
    mood: ['역사', '성찰'],
    coords: { lat: 37.1850, lng: 129.0530 },
    district: '미로면'
  },
  {
    id: 'lit-59',
    region: 'gangwon',
    title: '정선아리랑',
    author: '전래 민요',
    year: 1400,
    genre: '시',
    location: '정선 정선읍 아리랑센터',
    excerpt: '눈이 올라나 비가 올라나\n억수장마 질라나\n만수산 검은 구름이 막 모여든다',
    description: '600년 넘게 전승된 강원도 정선의 향토 민요로, 산골 사람들의 설움과 그리움을 구성진 가락에 담았다. 고려 말 유신들이 송도를 떠나 정선에 은거하며 부른 노래가 시원으로 전해진다. 정선읍 아리랑센터에서 정선아리랑을 체험할 수 있다.',
    mood: ['그리움', '슬픔'],
    coords: { lat: 37.3810, lng: 128.6608 },
    district: '정선읍'
  },
  {
    id: 'lit-60',
    region: 'gangwon',
    title: '토지',
    author: '박경리',
    year: 1994,
    genre: '소설',
    location: '원주 단구동 박경리문학공원',
    excerpt: '사람의 목숨은 잡초 같아서 밟히고 뜯겨도 다시 돋아나는 법이다.',
    description: '동학농민운동부터 광복까지 한 가문의 흥망을 그린 한국 최대의 대하소설. 박경리가 1980년 원주로 이주해 4부와 5부를 집필하고 1994년 완성했다. 원주 단구동에 박경리문학공원과 문학의 집이 있다.',
    mood: ['역사', '성찰'],
    coords: { lat: 37.3520, lng: 127.9450 },
    district: '단구동'
  },
  {
    id: 'lit-61',
    region: 'gangwon',
    title: '꿈꾸는 식물',
    author: '이외수',
    year: 1978,
    genre: '소설',
    location: '화천 상서면 감성마을 이외수문학관',
    excerpt: '나는 나의 환경이 허용하는 매우 좁은 자유의 한계 속에서 이리저리 서성거리기만 하는 나약한 짐승이었다.',
    description: '원시적 생명력과 환상적 수법으로 인간 존재의 근원을 탐색한 이외수의 첫 장편소설. 강원도 산골의 거친 자연이 작품 세계의 토양이다. 화천 감성마을에 이외수문학관이 있다.',
    mood: ['고독', '성찰'],
    coords: { lat: 38.1580, lng: 127.6830 },
    district: '상서면'
  },

  // ── 충청북도 ──
  {
    id: 'lit-6',
    region: 'okcheon',
    title: '향수',
    author: '정지용',
    year: 1927,
    genre: '시',
    location: '옥천 하계리',
    excerpt: '넓은 벌 동쪽 끝으로\n옛이야기 지줄대는 실개천이 회돌아 나가고,\n얼룩백이 황소가\n해설피 금빛 게으른 울음을 우는 곳',
    description: '고향 옥천의 풍경을 감각적 언어로 그린, 한국인이 가장 사랑하는 시 중 하나. 시에 묘사된 실개천과 들판은 옥천 하계리의 실제 풍경이다. 옥천에 정지용문학관이 있다.',
    mood: ['그리움', '서정'],
    coords: { lat: 36.3150, lng: 127.5816 },
    district: '하계리'
  },
  {
    id: 'lit-7',
    region: 'chungnam',
    title: '관촌수필',
    author: '이문구',
    year: 1977,
    genre: '소설',
    location: '보령 대천',
    excerpt: '이 고장은 물이 좋고 들이 넓어서, 예부터 인심이 후했다고 한다.',
    description: '산업화에 사라져가는 농촌 공동체를 토속적 언어로 기록한 연작 소설. 보은군 관촌의 사계절과 사람들이 실제 배경이다.',
    mood: ['그리움', '서정'],
    coords: { lat: 36.3534, lng: 126.5898 },
    district: '대천'
  },

  // ── 충청남도 ──
  {
    id: 'lit-8',
    region: 'chungnam',
    title: '님의 침묵',
    author: '한용운',
    year: 1926,
    genre: '시',
    location: '공주 마곡사',
    excerpt: '님은 갔습니다.\n아아, 사랑하는 나의 님은 갔습니다.\n푸른 산빛을 깨치고 단풍나무 숲을 향하여 난\n작은 길을 걸어서, 차마 떨치고 갔습니다.',
    description: '"님"에 대한 그리움을 통해 조국 독립의 염원을 노래한 시집. 한용운이 공주 마곡사 등지에서 수행하며 집필했다. 마곡사 경내에 한용운 기념관이 있다.',
    mood: ['그리움', '저항'],
    coords: { lat: 36.5582, lng: 127.0126 },
    district: '마곡사'
  },
  {
    id: 'lit-9',
    region: 'chungnam',
    title: '상록수',
    author: '심훈',
    year: 1935,
    genre: '소설',
    location: '당진 필경사',
    excerpt: '그 여자는 이를 악물었다. 배우자, 가르치자, 이 땅의 흙과 함께 살자.',
    description: '농촌 계몽 운동에 헌신하는 두 청년의 사랑과 희생을 그린 소설. 심훈이 당진 필경사에서 직접 집필했다. 당진에 심훈기념관과 필경사가 보존되어 있다.',
    mood: ['저항', '사랑'],
    coords: { lat: 36.9522, lng: 126.7706 },
    district: '필경사'
  },
  {
    id: 'lit-10',
    region: 'buyeo',
    title: '껍데기는 가라',
    author: '신동엽',
    year: 1967,
    genre: '시',
    location: '부여 신동엽문학관',
    excerpt: '껍데기는 가라.\n사월도 알맹이만 남고\n껍데기는 가라.',
    description: '4·19 혁명의 정신을 노래한 참여시의 대표작. 부여 출신 신동엽 시인이 백제의 고도에서 역사 의식을 길러냈다. 부여에 신동엽문학관이 있다.',
    mood: ['저항'],
    coords: { lat: 36.2776, lng: 126.9094 },
    district: '신동엽문학관'
  },

  // ── 경상북도 ──
  {
    id: 'lit-11',
    region: 'gyeongju',
    title: '무녀도',
    author: '김동리',
    year: 1936,
    genre: '소설',
    location: '경주 동리목월문학관',
    excerpt: '모화는 무당이었다.\n그의 딸 낭이는 그런 어머니가 싫었다.',
    description: '토착 신앙과 외래 종교의 충돌을 통해 한국적 정체성을 탐구한 소설. 경주의 토속적 분위기가 이야기의 배경이다.',
    mood: ['성찰'],
    coords: { lat: 35.7850, lng: 129.3340 },
    district: '동리목월문학관'
  },
  {
    id: 'lit-12',
    region: 'gyeongju',
    title: '나그네',
    author: '박목월',
    year: 1946,
    genre: '시',
    location: '경주',
    excerpt: '강나루 건너서\n밀밭 길을\n구름에 달 가듯이\n가는 나그네',
    description: '향토적 서정의 극치를 보여주는 한국 자연시의 대표작. 경주 출신 박목월이 고향의 들길 풍경을 담았다.',
    mood: ['서정', '그리움'],
    coords: { lat: 35.7850, lng: 129.3340 },
    district: '경주'
  },
  {
    id: 'lit-13',
    region: 'gyeongbuk',
    title: '승무',
    author: '조지훈',
    year: 1940,
    genre: '시',
    location: '영양 주실마을',
    excerpt: '얇은 사 하이얀 고깔은\n고이 접어서 나빌레라.',
    description: '승무하는 여인의 움직임을 한국적 미의식으로 형상화한 시. 영양 주실마을에서 자란 조지훈의 전통미 탐구가 돋보인다. 영양에 조지훈문학관이 있다.',
    mood: ['서정', '성찰'],
    coords: { lat: 36.6720, lng: 129.1126 },
    district: '주실마을'
  },

  // ── 대구 ──
  {
    id: 'lit-26',
    region: 'daegu',
    title: '빼앗긴 들에도 봄은 오는가',
    author: '이상화',
    year: 1926,
    genre: '시',
    location: '대구 중구 계산동 이상화 고택',
    excerpt: '지금은 남의 땅 — 빼앗긴 들에도 봄은 오는가?',
    description: '빼앗긴 조국의 봄을 갈망한 일제강점기 저항시의 대표작. 대구에서 나고 자란 이상화의 울분이 담겨 있다. 대구 중구에 이상화 고택이 보존되어 있다.',
    mood: ['저항'],
    coords: { lat: 35.8672, lng: 128.5880 },
    district: '중구'
  },

  // ── 전라북도 ──
  {
    id: 'lit-14',
    region: 'gunsan',
    title: '탁류',
    author: '채만식',
    year: 1938,
    genre: '소설',
    location: '군산 내항',
    excerpt: '예로부터 금강은 탁류였다.\n맑을 날이 드물고, 흐린 날이 많았다.',
    description: '식민지 시대 조선인의 삶을 금강 하구의 탁한 물줄기에 빗대어 풍자한 리얼리즘 장편. 군산 내항 일대가 소설의 주요 무대이다. 군산 근대역사박물관 근처에서 소설 속 장소들을 찾을 수 있다.',
    mood: ['아픔'],
    coords: { lat: 35.9908, lng: 126.7120 },
    district: '내항'
  },
  {
    id: 'lit-15',
    region: 'namwon',
    title: '혼불',
    author: '최명희',
    year: 1996,
    genre: '소설',
    location: '남원 사매면 혼불문학관',
    excerpt: '종가의 큰며느리로 가는 가마 위에서, 여자의 몸속에 혼불이 일었다.',
    description: '조선 말기 양반가 며느리의 삶을 통해 한국 여성의 역사를 조명한 대하소설. 남원의 풍습과 언어를 정밀하게 기록한 한국어의 보고(寶庫)로 평가된다. 남원에 혼불문학관이 있다.',
    mood: ['그리움', '사랑'],
    coords: { lat: 35.4813, lng: 127.3199 },
    district: '사매면'
  },
  {
    id: 'lit-16',
    region: 'gochang',
    title: '국화 옆에서',
    author: '서정주',
    year: 1948,
    genre: '시',
    location: '고창 미당시문학관',
    excerpt: '한 송이의 국화꽃을 피우기 위해\n봄부터 소쩍새는\n그렇게 울었나 보다.',
    description: '꽃 한 송이에 담긴 시간과 인고의 의미를 노래한 미당 서정주의 대표작. 고창에서 나고 자란 시인의 자연 감각이 녹아 있다. 고창에 미당시문학관이 있다.',
    mood: ['서정', '성찰'],
    coords: { lat: 35.5355, lng: 126.6099 },
    district: '미당시문학관'
  },

  // ── 광주 ──
  {
    id: 'lit-19',
    region: 'gwangju',
    title: '소년이 온다',
    author: '한강',
    year: 2014,
    genre: '소설',
    location: '광주 동구 옛 전남도청',
    excerpt: '파란 빛이었다.\n네 얼굴 위로 파란 빛이 번지고 있었다.',
    description: '5·18 광주민주화운동의 비극을 열다섯 살 소년의 시선으로 그린 소설. 전남도청과 광주 시내가 핵심 무대이다. 전남도청 옛 건물이 5·18 민주화운동 기록관으로 보존되어 있다.',
    mood: ['아픔', '저항'],
    coords: { lat: 35.1467, lng: 126.9203 },
    district: '동구'
  },

  // ── 전라남도 ──
  {
    id: 'lit-17',
    region: 'beolgyo',
    title: '태백산맥',
    author: '조정래',
    year: 1989,
    genre: '소설',
    location: '벌교 소화다리',
    excerpt: '소화다리 위로 찬바람이 불어왔다.\n벌교 읍내가 저물녘 어둠 속으로 잠기고 있었다.',
    description: '여순사건부터 6·25전쟁까지 좌우 이념 대립의 비극을 그린 전 10권의 대하소설. 벌교 소화다리와 읍내가 이야기의 중심 무대이다. 벌교에 태백산맥문학관이 있으며 소설 속 장소들을 탐방할 수 있다.',
    mood: ['아픔', '저항'],
    coords: { lat: 34.8492, lng: 127.3523 },
    district: '소화다리'
  },
  {
    id: 'lit-18',
    region: 'beolgyo',
    title: '무진기행',
    author: '김승옥',
    year: 1964,
    genre: '소설',
    location: '순천 순천만문학관',
    excerpt: '무진에 명산물이 있다면 안개다.\n아침에 잠자리에서 일어나서 밖으로 나오면,\n밤사이에 진주해 온 적군들처럼 안개가 무진을 둘러싸고 있는 것이었다.',
    description: '안개에 잠긴 가상의 도시 "무진"을 배경으로 한 남자의 내면을 그린 모더니즘 소설의 걸작. 무진의 모델은 순천 일대로 알려져 있다.',
    mood: ['고독', '성찰'],
    coords: { lat: 34.8946, lng: 127.5158 },
    district: '순천만'
  },

  // ── 울산 ──
  {
    id: 'lit-28',
    region: 'ulsan',
    title: '처용가',
    author: '작자 미상',
    year: 879,
    genre: '향가',
    location: '울산 처용암',
    excerpt: '서라벌 달 밝은 밤에\n밤들이 노닐다가\n들어와 자리를 보니\n다리가 넷이로구나.',
    description: '아내를 범한 역신 앞에서 노래와 춤으로 물리친 처용의 이야기를 담은 신라 향가. 삼국유사에 처용이 울산 개운포에서 나타났다는 기록이 전한다. 울산에서 매년 처용문화제가 열린다.',
    mood: ['서정'],
    coords: { lat: 35.4672, lng: 129.3489 },
    district: '처용암'
  },

  // ── 경상남도 ──
  {
    id: 'lit-20',
    region: 'hadong',
    title: '토지',
    author: '박경리',
    year: 1994,
    genre: '소설',
    location: '하동 악양면 평사리',
    excerpt: '땅은 거기 그대로 있고, 사람만 오고 갈 뿐이었다.',
    description: '구한말부터 해방까지 민족의 역사를 그린 전 16권의 대하소설. 하동 악양면 평사리가 서사의 출발점이다. 악양면에 토지문학관과 최참판댁이 복원되어 있다.',
    mood: ['그리움', '아픔'],
    coords: { lat: 35.1559, lng: 127.6884 },
    district: '악양면'
  },
  {
    id: 'lit-21',
    region: 'tongyeong',
    title: '깃발',
    author: '유치환',
    year: 1936,
    genre: '시',
    location: '통영 청마문학관',
    excerpt: '이것은 소리 없는 아우성.\n저 푸른 해원(海原)을 향하여 흔드는\n영원한 노스탤지어의 손수건.',
    description: '바다를 향한 그리움과 존재의 고독을 노래한 한국 서정시의 정수. 통영 바다를 바라보며 쓴 청마 유치환의 대표작이다. 통영에 청마문학관이 있다.',
    mood: ['그리움', '고독'],
    coords: { lat: 34.8450, lng: 128.4353 },
    district: '청마문학관'
  },
  {
    id: 'lit-22',
    region: 'gyeongnam',
    title: '마당 깊은 집',
    author: '김원일',
    year: 1988,
    genre: '소설',
    location: '김해 진영',
    excerpt: '우리 집은 마당이 깊었다.\n대문에서 안마당까지 한참을 걸어 들어가야 했다.',
    description: '6·25 전쟁 직후 피난민들이 모여 사는 한 집을 배경으로 전쟁의 상처와 삶의 회복을 그린 성장소설. 김해 진영의 한 대가족 집이 실제 배경이다.',
    mood: ['그리움', '아픔'],
    coords: { lat: 35.3141, lng: 128.7701 },
    district: '진영'
  },

  // ── 부산 ──
  {
    id: 'lit-27',
    region: 'busan',
    title: '광장',
    author: '최인훈',
    year: 1961,
    genre: '소설',
    location: '부산 부산항',
    excerpt: '이명준은 난간에 기대서서 바다를 바라보았다.\n남쪽도 북쪽도 아닌, 그 어디로 가는 배 위에서.',
    description: '남북 분단 사이에서 방황하는 지식인의 비극을 그린 관념 소설. 주인공이 부산항에서 중립국행 배를 타는 장면은 분단 문학의 상징이다.',
    mood: ['고독', '성찰'],
    coords: { lat: 35.1223, lng: 129.0491 },
    district: '부산항'
  },

  // ── 제주도 ──
  {
    id: 'lit-23',
    region: 'jeju',
    title: '순이 삼촌',
    author: '현기영',
    year: 1978,
    genre: '소설',
    location: '제주 북촌리 너븐숭이',
    excerpt: '정월 어느 날, 순이 삼촌이 목을 매어 죽었다는 소식이 들려왔다.',
    description: '제주 4·3 사건의 비극을 한 마을의 기억을 통해 증언한 소설. 제주 북촌리 일대가 작품의 배경이다. 제주 4·3 평화공원에서 그 역사를 기릴 수 있다.',
    mood: ['아픔'],
    coords: { lat: 33.5460, lng: 126.6888 },
    district: '북촌리'
  },
  {
    id: 'lit-24',
    region: 'jeju',
    title: '이어도',
    author: '이청준',
    year: 1974,
    genre: '소설',
    location: '제주 남쪽 바다',
    excerpt: '이어도사나, 이어도사나.\n바다 저 너머 이어도가 있다고 해녀들은 노래했다.',
    description: '전설의 섬 이어도를 소재로 이상향에 대한 인간의 갈망을 그린 소설. 제주 해녀들의 이어도 노래가 이야기의 중심 모티프이다.',
    mood: ['그리움', '성찰'],
    coords: { lat: 32.1230, lng: 125.1824 },
    district: '남쪽바다'
  },

  // ── 강릉 ──
  {
    id: 'lit-29',
    region: 'gangneung',
    title: '관동별곡',
    author: '정철',
    year: 1580,
    genre: '가사',
    location: '강릉 경포대',
    excerpt: '강호에 병이 깊어 죽림에 누웠더니\n관동 팔백 리에 방면을 맡기시니',
    description: '관동 지방의 절경을 유람하며 노래한 기행가사의 최고봉. 강원도 관찰사로 부임한 정철이 경포대 등 관동팔경을 순유한 기록이다. 강릉 경포대에서 관동별곡의 풍경을 느낄 수 있다.',
    mood: ['서정'],
    coords: { lat: 37.7950, lng: 128.8967 },
    district: '경포대'
  },

  // ── 안동 ──
  {
    id: 'lit-30',
    region: 'andong',
    title: '광야',
    author: '이육사',
    year: 1946,
    genre: '시',
    location: '안동 도산면',
    excerpt: '까마득한 날에\n하늘이 처음 열리고\n어디 닭 우는 소리 들렸으랴',
    description: '암흑 같은 식민지 현실에서 광복의 그날을 노래한 저항시의 대표작. 안동 도산면에서 태어난 이육사의 불굴의 의지가 담겨 있다. 안동에 이육사문학관이 있다.',
    mood: ['저항'],
    coords: { lat: 36.7390, lng: 128.8632 },
    district: '도산면'
  },

  // ── 목포 ──
  {
    id: 'lit-31',
    region: 'mokpo',
    title: '추석전야',
    author: '박화성',
    year: 1925,
    genre: '소설',
    location: '목포 목포문학관',
    excerpt: '목포의 낯은 보기에 참 애처로웁다.',
    description: '목포 방직공장 여공의 삶을 그린 한국 최초 여성 소설가의 등단작. 일제강점기 목포의 노동 현실과 여성의 고단함이 담겨 있다. 목포에 박화성 문학거리가 조성되어 있다.',
    mood: ['아픔'],
    coords: { lat: 34.7928, lng: 126.4169 },
    district: '목포문학관'
  }
,
  // ═══ 충청북도 추가 ═══
  {
    id: 'lit-62',
    region: 'okcheon',
    title: '유리창',
    author: '정지용',
    year: 1930,
    genre: '시',
    location: '옥천 정지용문학관',
    excerpt: '유리에 차고 슬픈 것이 어린거린다.\n열없이 붙어서서 입김을 흐리우니\n길들은 양 언 날개를 파닥거린다.',
    description: '유리창에 비친 죽은 아이의 환영을 노래한 정지용의 대표 서정시. 시인의 고향 옥천의 겨울 풍경이 시의 정서적 바탕이다. 옥천 정지용문학관에서 시인의 육필 원고를 볼 수 있다.',
    mood: ['슬픔', '서정'],
    coords: { lat: 36.3150, lng: 127.5816 },
    district: '하계리'
  },
  {
    id: 'lit-63',
    region: 'okcheon',
    title: '호수',
    author: '정지용',
    year: 1939,
    genre: '시',
    location: '옥천 정지용문학관',
    excerpt: '얼굴 하나야\n손바닥 둘로\n폭 가리지만,\n보고 싶은 마음\n호수만 하니\n눈 감을 밖에.',
    description: '사랑하는 이를 그리워하는 마음을 호수에 비유한 짧고 아름다운 시. 정지용 시 세계의 응축미를 대표한다. 옥천 정지용문학관에서 시비를 만날 수 있다.',
    mood: ['사랑', '그리움'],
    coords: { lat: 36.3150, lng: 127.5816 },
    district: '하계리'
  },
  {
    id: 'lit-64',
    region: 'chungbuk',
    title: '농무',
    author: '신경림',
    year: 1973,
    genre: '시',
    location: '충주 신경림문학관',
    excerpt: '징이 울린다 막이 내렸다\n오이밭 텃머리의 반달이 하나\n꽉 닫힌 눈두덩에 쌀보리 바람이 분다',
    description: '산업화에 밀려난 농민들의 울분을 북소리와 춤사위로 형상화한 민중시의 대표작. 충주 출신 시인이 고향 농촌의 피폐한 현실을 시로 옮겼다. 충주에 신경림문학관이 있다.',
    mood: ['저항', '서민'],
    coords: { lat: 36.9910, lng: 127.9259 },
    district: '충주시'
  },

  // ═══ 충청남도 추가 ═══
  {
    id: 'lit-65',
    region: 'chungnam',
    title: '그날이 오면',
    author: '심훈',
    year: 1930,
    genre: '시',
    location: '당진 필경사',
    excerpt: '그날이 오면 그날이 오면은\n삼각산이 일어나 더덩실 춤이라도 추고\n한강물이 뒤집혀 용솟음칠 그날이',
    description: '광복의 그날을 갈망하며 온 천지가 기뻐 춤추는 모습을 노래한 저항시. 심훈이 당진 필경사에서 민족 해방의 염원을 불태우며 쓴 작품이다. 당진 심훈기념관에서 육필 원고를 볼 수 있다.',
    mood: ['저항', '희망'],
    coords: { lat: 36.9522, lng: 126.7706 },
    district: '필경사'
  },
  {
    id: 'lit-66',
    region: 'chungnam',
    title: '절명시',
    author: '성삼문',
    year: 1456,
    genre: '시',
    location: '홍성 성삼문 유허지',
    excerpt: '이 몸이 죽어 가서 무엇이 될꼬 하니\n봉래산 제일봉에 낙락장송 되었다가\n백설이 만건곤할 제 독야청청하리라',
    description: '사육신 성삼문이 단종 복위 실패 후 형장에서 읊은 시조. 홍성 출신 성삼문의 불사이군 절개가 담겨 있다. 홍성에 성삼문 유허지와 사당이 남아 있다.',
    mood: ['비장', '절개'],
    coords: { lat: 36.6013, lng: 126.6610 },
    district: '홍성읍'
  },
  {
    id: 'lit-67',
    region: 'chungnam',
    title: '나룻배와 행인',
    author: '한용운',
    year: 1926,
    genre: '시',
    location: '홍성 한용운 생가지',
    excerpt: '나는 나룻배\n당신은 행인\n당신은 흙발로 나를 짓밟습니다.\n나는 당신을 안고 물을 건넙니다.',
    description: '사랑의 헌신을 나룻배와 행인의 관계로 형상화한 시. 한용운의 고향 홍성에서 그의 자기희생적 사랑관이 자라났다. 홍성 결성면에 한용운 생가지가 보존되어 있다.',
    mood: ['사랑', '헌신'],
    coords: { lat: 36.5580, lng: 126.5890 },
    district: '결성면'
  },
  {
    id: 'lit-68',
    region: 'chungnam',
    title: '풀꽃',
    author: '나태주',
    year: 1996,
    genre: '시',
    location: '공주 나태주풀꽃문학관',
    excerpt: '자세히 보아야\n예쁘다\n\n오래 보아야\n사랑스럽다\n\n너도 그렇다',
    description: '작고 소박한 풀꽃에서 사랑의 진실을 발견하는 시. 공주에서 오래 교편을 잡은 시인이 일상 속 아름다움을 노래했다. 공주 제민천변에 나태주풀꽃문학관이 있다.',
    mood: ['사랑', '서정'],
    coords: { lat: 36.4514, lng: 127.1190 },
    district: '공주시'
  },

  // ═══ 경상북도·대구 추가 ═══
  {
    id: 'lit-69',
    region: 'andong',
    title: '청포도',
    author: '이육사',
    year: 1939,
    genre: '시',
    location: '안동 이육사문학관',
    excerpt: '내 고장 칠월은\n청포도가 익어 가는 시절\n\n이 마을 전설이 주저리주저리 열리고\n먼 데 하늘이 꿈꾸며 알알이 들어와 박혀',
    description: '광복을 청포도가 익어가는 계절에 비유한 이육사의 대표 서정시. 안동의 자연 풍광이 시인의 민족적 이상과 결합되어 있다. 안동 이육사문학관에서 시인의 삶을 조명할 수 있다.',
    mood: ['희망', '서정'],
    coords: { lat: 36.5684, lng: 128.7294 },
    district: '도산면'
  },
  {
    id: 'lit-70',
    region: 'andong',
    title: '절정',
    author: '이육사',
    year: 1940,
    genre: '시',
    location: '안동 이육사문학관',
    excerpt: '매운 계절의 채찍에 갈겨\n마침내 북방으로 휩쓸려 오다\n\n하늘도 그만 지쳐 끝난 고비에\n서릿발 칼날진 그 위에 서다',
    description: '극한의 역경 속에서도 굴하지 않는 의지를 노래한 저항시의 절정. 독립운동가이자 시인인 이육사의 불굴의 정신이 안동의 험준한 산세와 겹친다. 이육사문학관에서 17번 투옥된 시인의 생애를 확인할 수 있다.',
    mood: ['저항', '비장'],
    coords: { lat: 36.5684, lng: 128.7294 },
    district: '도산면'
  },
  {
    id: 'lit-71',
    region: 'andong',
    title: '도산십이곡',
    author: '이황',
    year: 1565,
    genre: '시',
    location: '안동 도산서원',
    excerpt: '이런들 엇더하며 져런들 엇더하리\n초야우생이 이렇다 엇더하리\n하물며 천석고황을 고쳐 무슨하리오',
    description: '자연에 묻혀 학문하는 삶의 즐거움을 노래한 퇴계 이황의 시조 12수. 도산서원에서 제자를 가르치며 지은 작품으로, 성리학적 이상이 안동의 산수에 녹아 있다. 안동 도산서원은 유네스코 세계문화유산으로 등재되어 있다.',
    mood: ['성찰', '자연'],
    coords: { lat: 36.7275, lng: 128.8507 },
    district: '도산면'
  },
  {
    id: 'lit-72',
    region: 'gyeongju',
    title: '제망매가',
    author: '월명사',
    year: 760,
    genre: '시',
    location: '경주 사천왕사지',
    excerpt: '생사 길은\n예 있으매 머뭇거리고\n나는 간다는 말도\n못다 이르고 어찌 갑니까',
    description: '죽은 누이를 추모하며 부른 신라 향가로, 한국 문학사상 가장 오래된 추도시. 월명사가 사천왕사에서 피리를 불며 누이의 명복을 빌었다는 기록이 전한다. 경주 사천왕사지에서 천삼백 년 전의 슬픔을 느낄 수 있다.',
    mood: ['슬픔', '그리움'],
    coords: { lat: 35.8283, lng: 129.2321 },
    district: '낭산'
  },
  {
    id: 'lit-73',
    region: 'gyeongju',
    title: '나그네',
    author: '박목월',
    year: 1946,
    genre: '시',
    location: '경주 동리목월문학관',
    excerpt: '강나루 건너서\n밀밭 길을\n\n구름에 달 가듯이\n가는 나그네',
    description: '한국적 자연 속을 떠도는 나그네의 서정을 노래한 청록파 시의 대표작. 경주의 들판과 강나루가 시의 원풍경이 되었다. 경주 동리목월문학관에서 시인의 작품 세계를 만날 수 있다.',
    mood: ['서정', '방랑'],
    coords: { lat: 35.8562, lng: 129.2247 },
    district: '동리목월문학관'
  },
  {
    id: 'lit-74',
    region: 'gyeongju',
    title: '추야우중',
    author: '최치원',
    year: 885,
    genre: '시',
    location: '경주 남산',
    excerpt: '秋風唯苦吟 世路少知音\n窓外三更雨 燈前萬里心',
    description: '가을밤 빗소리 속에서 먼 고국을 그리며 읊은 최치원의 칠언절구. 신라의 천재 문인이 당나라에서 돌아와 경주에 머물며 고독한 심회를 토로했다. 경주 남산 일대에서 최치원의 유적을 찾을 수 있다.',
    mood: ['고독', '그리움'],
    coords: { lat: 35.8100, lng: 129.2200 },
    district: '남산'
  },
  {
    id: 'lit-75',
    region: 'daegu',
    title: '나의 침실로',
    author: '이상화',
    year: 1923,
    genre: '시',
    location: '대구 중구 이상화 고택',
    excerpt: '마돈나 지금은 밤 — 어두운 밤\n나의 침실로, 나의 침실로\n밤이다, 죽음 같은 밤.',
    description: '식민지 현실의 어둠 속에서 생명과 자유를 갈구하는 낭만적 저항시. 대구에서 나고 자란 이상화의 청년기 열정이 담겨 있다. 대구 중구에 이상화 고택이 보존되어 있다.',
    mood: ['저항', '낭만'],
    coords: { lat: 35.8672, lng: 128.5880 },
    district: '중구'
  },
  {
    id: 'lit-76',
    region: 'daegu',
    title: '봄은 고양이로다',
    author: '이장희',
    year: 1924,
    genre: '시',
    location: '대구 달성공원',
    excerpt: '꽃가루와 같이 부드러운 고양이의 털에\n고운 봄의 향기가 어리우도다.\n\n금방울과 같이 호동그란 고양이의 눈에\n미친 봄의 불길이 흐르도다.',
    description: '봄의 감각을 고양이의 이미지로 포착한 감각주의 시의 선구적 작품. 대구 출신 시인 이장희의 예민한 미의식이 빛난다. 대구 달성공원에서 근대 문학의 향기를 느낄 수 있다.',
    mood: ['서정', '감각'],
    coords: { lat: 35.8750, lng: 128.5828 },
    district: '달성공원'
  },
  {
    id: 'lit-77',
    region: 'yeongyang',
    title: '젊은 날의 초상',
    author: '이문열',
    year: 1981,
    genre: '소설',
    location: '영양 두들마을 이문열문학관',
    excerpt: '그해 겨울은 이상하리만큼 일찍 시작되었다.',
    description: '예술과 사상 사이에서 방황하는 청년의 정신적 편력을 그린 자전적 소설. 영양 두들마을에서 자란 작가의 고향 체험이 서사의 뿌리가 된다. 영양에 이문열문학관과 두들마을 문학의 거리가 있다.',
    mood: ['성찰', '방황'],
    coords: { lat: 36.6720, lng: 129.1126 },
    district: '주실마을'
  },

  // ═══ 전라북도 추가 ═══
  {
    id: 'lit-78',
    region: 'jeonbuk',
    title: '정읍사',
    author: '작자 미상',
    year: 500,
    genre: '시',
    location: '정읍 정읍사공원',
    excerpt: '달하 노피곰 도다샤\n어긔야 머리곰 비취오시라\n어긔야 어강됴리\n아으 다롱디리',
    description: '행상 나간 남편을 기다리는 아내의 마음을 달에게 호소한 백제 가요. 현존하는 유일한 백제 노래로, 정읍 지역에서 전승되었다. 정읍시에 정읍사공원과 시비가 있다.',
    mood: ['그리움', '기다림'],
    coords: { lat: 35.5699, lng: 126.8562 },
    district: '정읍시'
  },
  {
    id: 'lit-79',
    region: 'namwon',
    title: '춘향가',
    author: '판소리',
    year: 1700,
    genre: '소설',
    location: '남원 광한루원',
    excerpt: '이리 오너라 업고 놀자\n사랑 사랑 사랑 내 사랑이야\n이히 사랑이로구나 아마도 내 사랑이야',
    description: '이몽룡과 성춘향의 사랑을 노래한 판소리 다섯 마당의 하나. 남원 광한루에서 두 사람이 만나는 장면이 이야기의 시작이다. 남원 광한루원과 춘향테마파크에서 작품 속 세계를 체험할 수 있다.',
    mood: ['사랑', '해학'],
    coords: { lat: 35.4136, lng: 127.3893 },
    district: '광한루'
  },
  {
    id: 'lit-80',
    region: 'gochang',
    title: '자화상',
    author: '서정주',
    year: 1936,
    genre: '시',
    location: '고창 미당시문학관',
    excerpt: '애비는 종이었다. 밤이 깊어도 오지 않았다.\n파뿌리같이 늙은 할머니와\n대추꽃이 한 주 서 있을 뿐이었다.',
    description: '자신의 출생과 혈통을 정면으로 응시하며 시인의 운명을 선언한 미당의 초기 대표작. 고창에서 태어나 자란 시인의 원초적 생명력이 분출한다. 고창 미당시문학관에서 시인의 전 생애를 조망할 수 있다.',
    mood: ['운명', '생명'],
    coords: { lat: 35.5355, lng: 126.6099 },
    district: '미당시문학관'
  },
  {
    id: 'lit-81',
    region: 'gunsan',
    title: '태평천하',
    author: '채만식',
    year: 1938,
    genre: '소설',
    location: '군산 채만식문학관',
    excerpt: '윤직원 영감은 만사가 태평이었다. 세상이 아무렇게 굴러가든 집안이 뒤집히든 만사가 태평이었다.',
    description: '친일 부호 윤직원의 무지와 탐욕을 풍자한 채만식의 세태소설. 군산의 식민지 경제 구조가 소설의 배경이다. 군산 채만식문학관에서 작가의 풍자 정신을 느낄 수 있다.',
    mood: ['풍자', '세태'],
    coords: { lat: 35.9908, lng: 126.7120 },
    district: '내항'
  },
  {
    id: 'lit-82',
    region: 'jeonju',
    title: '난초',
    author: '이병기',
    year: 1939,
    genre: '시',
    location: '전주 한옥마을 이병기 생가터',
    excerpt: '나는 난초를 기른다.\n향기로운 꽃을 위하여서가 아니라\n그 푸르른 잎을 보기 위하여서다.',
    description: '난초의 푸른 잎에서 선비의 지조를 발견한 시조 혁신의 선구자 이병기의 대표 연시조. 전주에서 태어나 시조 부흥 운동을 이끈 가람의 정신이 담겨 있다. 전주 한옥마을에서 가람의 문학적 발자취를 더듬을 수 있다.',
    mood: ['성찰', '절개'],
    coords: { lat: 35.8155, lng: 127.1529 },
    district: '한옥마을'
  },
  {
    id: 'lit-83',
    region: 'jeonbuk',
    title: '꽃덤불',
    author: '신석정',
    year: 1955,
    genre: '시',
    location: '부안 신석정문학관',
    excerpt: '꽃덤불 옆으로 가서\n꽃덤불 사이로 들어가고 싶은 날.\n달빛 아래서 속삭이고 싶은 날.',
    description: '꽃덤불 속으로 걸어 들어가고 싶은 동경을 노래한 전원시인 신석정의 대표작. 전북 부안에서 평생 자연과 함께 살며 시를 쓴 시인의 세계가 담겨 있다. 부안 변산에 신석정문학관이 있다.',
    mood: ['서정', '자연'],
    coords: { lat: 35.7285, lng: 126.7338 },
    district: '부안읍'
  },

  // ═══ 광주·전라남도 추가 ═══
  {
    id: 'lit-84',
    region: 'gwangju',
    title: '봄날',
    author: '임철우',
    year: 1997,
    genre: '소설',
    location: '광주 동구 금남로',
    excerpt: '오월이었다. 시내 한복판에 총소리가 울려퍼지고 있었다.',
    description: '5·18 광주민주화운동의 열흘을 증언자의 기억을 통해 복원한 장편소설. 금남로와 전남도청 일대가 소설의 핵심 무대이다. 광주 금남로에서 소설 속 오월의 현장을 걸을 수 있다.',
    mood: ['아픔', '저항'],
    coords: { lat: 35.1530, lng: 126.9150 },
    district: '금남로'
  },
  {
    id: 'lit-85',
    region: 'jeonnam',
    title: '모란이 피기까지는',
    author: '김영랑',
    year: 1934,
    genre: '시',
    location: '강진 김영랑 생가',
    excerpt: '모란이 피기까지는\n나는 아직 나의 봄을 기다리고 있을 테요\n모란이 뚝뚝 떨어져 버린 날\n나는 비로소 봄을 여읜 설움에 잠길 테요',
    description: '모란꽃의 피고 짐을 통해 기다림과 상실의 정서를 노래한 순수 서정시의 정수. 강진에서 태어나 자란 시인의 섬세한 감수성이 남도의 풍토와 어우러진다. 강진읍에 김영랑 생가가 보존되어 있다.',
    mood: ['그리움', '서정'],
    coords: { lat: 34.6425, lng: 126.7672 },
    district: '강진읍'
  },
  {
    id: 'lit-86',
    region: 'haenam',
    title: '어부사시사',
    author: '윤선도',
    year: 1651,
    genre: '시',
    location: '해남 보길도 세연정',
    excerpt: '우는 것이 뻐꾸기가 프른 것이 버들숲에\n어촌 두어 집이 냇가에 있다\n잔잔한 물결에 봄빛이 떠오르도다',
    description: '봄·여름·가을·겨울 어부의 생활을 노래한 시조 40수로, 한국 시조 문학의 최고봉. 윤선도가 해남 보길도에 은거하며 지었다. 보길도 세연정과 윤선도원림이 국가 명승으로 지정되어 있다.',
    mood: ['자연', '서정'],
    coords: { lat: 34.1500, lng: 126.5500 },
    district: '보길도'
  },
  {
    id: 'lit-87',
    region: 'beolgyo',
    title: '사평역에서',
    author: '곽재구',
    year: 1983,
    genre: '시',
    location: '순천 사평역',
    excerpt: '막차는 좀처럼 오지 않았다\n대합실 밖에는 밤새 송이눈이 쌓이고\n흰 보리라도 한 가마 팔아야 할\n궁상맞은 시골 아낙의 마음은',
    description: '눈 내리는 작은 간이역에서 서민들의 삶의 애환을 그린 서정시. 순천 사평역의 허름한 대합실이 시의 무대이다. 현재 사평역은 폐역이 되었으나 시비가 남아 문학 탐방지로 사랑받는다.',
    mood: ['서정', '서민'],
    coords: { lat: 34.9220, lng: 127.3710 },
    district: '순천시'
  },
  {
    id: 'lit-88',
    region: 'jeonnam',
    title: '성산별곡',
    author: '정철',
    year: 1560,
    genre: '시',
    location: '담양 식영정',
    excerpt: '어디서 흰 구름이 절로 절로 피어오르고\n찬 시내 떨어져 굽이굽이 흘러가니\n사시의 풍경이 유인을 머물게 하노라',
    description: '담양 성산의 사계절 풍경을 읊은 정철의 가사 작품. 식영정에서 바라본 산수의 아름다움이 유려한 가사체로 펼쳐진다. 담양 식영정과 소쇄원에서 정철의 가사 문학 현장을 만날 수 있다.',
    mood: ['자연', '서정'],
    coords: { lat: 35.2810, lng: 126.9320 },
    district: '남면'
  },
  {
    id: 'lit-89',
    region: 'jeonnam',
    title: '서편제',
    author: '이청준',
    year: 1976,
    genre: '소설',
    location: '장흥 이청준문학관',
    excerpt: '소리꾼 유봉은 그날부터 딸아이를 업고 남도 땅을 떠돌기 시작했다.',
    description: '판소리 서편제의 한을 아버지와 딸의 떠돎으로 형상화한 남도 문학의 대표작. 장흥 출신 작가가 남도 곳곳을 서사의 배경으로 삼았다. 장흥에 이청준문학관이 있으며, 보성 소리길도 조성되어 있다.',
    mood: ['한', '예술'],
    coords: { lat: 34.6818, lng: 126.9074 },
    district: '장흥읍'
  },
  {
    id: 'lit-90',
    region: 'jeonnam',
    title: '떠나가는 배',
    author: '박용철',
    year: 1930,
    genre: '시',
    location: '광양 박용철 생가',
    excerpt: '나 두 야 간다\n나의 이 젊은 나이를\n눈물로야 보내 드리우랴\n나 두 야 가련다',
    description: '떠남의 결의와 그에 따르는 슬픔을 노래한 시문학파의 대표작. 광양에서 태어난 시인이 고향을 떠나며 쓴 작품이다. 광양시에 박용철 생가와 문학 산책로가 있다.',
    mood: ['이별', '결의'],
    coords: { lat: 34.9410, lng: 127.5870 },
    district: '광양읍'
  },
  {
    id: 'lit-91',
    region: 'jeonnam',
    title: '사미인곡',
    author: '정철',
    year: 1588,
    genre: '시',
    location: '담양 송강정',
    excerpt: '이 몸 삼기실 제 님을 좇아 삼기시니\n한생연분이며 하늘 모를 일이로다\n나 하나 젊어 있고 님 하나 날 괴시니',
    description: '임금에 대한 그리움을 여인의 목소리로 노래한 정철의 가사. 담양에 유배되어 있던 시기에 쓴 작품으로, 충신의 연군지정이 담겨 있다. 담양 송강정에서 정철의 가사 문학 현장을 만날 수 있다.',
    mood: ['그리움', '충절'],
    coords: { lat: 35.2975, lng: 126.9410 },
    district: '남면'
  },
  {
    id: 'lit-92',
    region: 'jeonnam',
    title: '당신들의 천국',
    author: '이청준',
    year: 1976,
    genre: '소설',
    location: '고흥 소록도',
    excerpt: '섬에서의 첫날밤, 조백헌 원장은 어둠 속에서 바다 소리를 들었다.',
    description: '한센병 환자들의 격리된 삶을 통해 이상사회의 본질을 묻는 소설. 전남 고흥 소록도가 소설의 무대이다. 소록도 한센병 박물관에서 소설의 역사적 배경을 확인할 수 있다.',
    mood: ['성찰', '공동체'],
    coords: { lat: 34.4792, lng: 127.1036 },
    district: '소록도'
  },

  // ═══ 경상남도·울산 추가 ═══
  {
    id: 'lit-93',
    region: 'tongyeong',
    title: '꽃',
    author: '김춘수',
    year: 1952,
    genre: '시',
    location: '통영 김춘수유품전시관',
    excerpt: '내가 그의 이름을 불러 주기 전에는\n그는 다만\n하나의 몸짓에 지나지 않았다.\n\n내가 그의 이름을 불러 주었을 때\n그는 나에게로 와서\n꽃이 되었다.',
    description: '이름을 부름으로써 존재가 완성된다는 존재론적 통찰을 담은 한국 현대시의 대표작. 통영에서 태어난 시인의 사유가 바다의 도시에서 영글었다. 통영 김춘수유품전시관에서 시인의 세계를 만날 수 있다.',
    mood: ['성찰', '사랑'],
    coords: { lat: 34.8544, lng: 128.4333 },
    district: '청마문학관'
  },
  {
    id: 'lit-94',
    region: 'namhae',
    title: '구운몽',
    author: '김만중',
    year: 1689,
    genre: '소설',
    location: '남해 김만중유허지',
    excerpt: '화설 서역국 천축 나라에 대승선사 육관대사가 있으니 명산 영지를 두루 다니며 도를 닦았더라.',
    description: '꿈과 현실의 경계를 넘나드는 한국 고전소설의 대표작. 김만중이 남해 유배 시절 어머니를 위로하기 위해 지은 작품이다. 남해에 김만중유허지와 문학관이 있다.',
    mood: ['꿈', '성찰'],
    coords: { lat: 34.8096, lng: 127.9250 },
    district: '노량리'
  },
  {
    id: 'lit-95',
    region: 'gyeongnam',
    title: '귀천',
    author: '천상병',
    year: 1970,
    genre: '시',
    location: '창원 마산 천상병 생가터',
    excerpt: '나 하늘로 돌아가리라\n아름다운 이 세상 소풍 끝내는 날\n가서, 아름다웠더라고 말하리라.',
    description: '삶을 아름다운 소풍으로 비유한 천상병의 대표시. 경남 창녕에서 태어나 마산에서 유년을 보낸 시인의 천진한 세계관이 담겨 있다. 마산에서 시인의 문학적 발자취를 만날 수 있다.',
    mood: ['달관', '서정'],
    coords: { lat: 35.1799, lng: 128.5735 },
    district: '마산'
  },
  {
    id: 'lit-96',
    region: 'tongyeong',
    title: '김약국의 딸들',
    author: '박경리',
    year: 1962,
    genre: '소설',
    location: '통영 박경리기념관',
    excerpt: '김성수 약국은 이 고을에서 제일 큰 약방이었다.',
    description: '개화기 통영의 한 약국 가문 다섯 딸의 운명을 그린 가족사 소설. 박경리가 태어나고 자란 통영의 풍경과 인물이 작품에 녹아 있다. 통영 박경리기념관에서 작가의 생애를 조명할 수 있다.',
    mood: ['가족', '운명'],
    coords: { lat: 34.8544, lng: 128.4333 },
    district: '박경리기념관'
  },
  {
    id: 'lit-97',
    region: 'gyeongnam',
    title: '가고파',
    author: '이은상',
    year: 1933,
    genre: '시',
    location: '창원 마산 가고파거리',
    excerpt: '내 고향 남쪽 바다 그 파란 물 눈에 보이네\n꿈엔들 잊으리야 그 잔잔한 고향 바다\n지금도 그 물새들 날으리 가고파라',
    description: '고향 마산 바다를 그리워하며 쓴 국민 가곡의 원작 시. 마산 앞바다의 푸른 물결이 시의 원풍경이다. 마산 가고파거리에 이은상 시비가 있다.',
    mood: ['그리움', '향수'],
    coords: { lat: 35.1830, lng: 128.5710 },
    district: '마산'
  },
  {
    id: 'lit-98',
    region: 'gyeongnam',
    title: '논개',
    author: '변영로',
    year: 1923,
    genre: '시',
    location: '진주 촉석루',
    excerpt: '거룩한 분노는 종교보다도 깊고\n불붙는 정열은 사랑보다도 강한\n아 강낭콩꽃보다도 더 푸른\n그 물결 위에',
    description: '왜장을 안고 남강에 투신한 논개의 의기를 찬양한 시. 진주 촉석루에서 벌어진 실화가 시의 바탕이다. 진주 촉석루와 의기사에서 논개의 넋을 기릴 수 있다.',
    mood: ['비장', '의기'],
    coords: { lat: 35.1916, lng: 128.0850 },
    district: '촉석루'
  },
  {
    id: 'lit-99',
    region: 'gyeongnam',
    title: '모래톱 이야기',
    author: '김정한',
    year: 1966,
    genre: '소설',
    location: '김해 낙동강 하류',
    excerpt: '조마이섬은 갈대와 모래뿐인 하중도였다.',
    description: '낙동강 하류 모래톱에 사는 농민들이 개발 논리에 삶의 터전을 빼앗기는 이야기. 김해와 부산 사이 낙동강 하류의 하중도가 실제 배경이다. 을숙도와 낙동강 하구에서 소설 속 풍경의 흔적을 찾을 수 있다.',
    mood: ['저항', '서민'],
    coords: { lat: 35.1200, lng: 128.9600 },
    district: '낙동강'
  },

  // ═══ 부산 추가 ═══
  {
    id: 'lit-100',
    region: 'busan',
    title: '사하촌',
    author: '김정한',
    year: 1936,
    genre: '소설',
    location: '부산 사하구',
    excerpt: '절에서 내려다보면 기왓장이 빽빽하고 좁은 골목이 어지러운 마을이 보인다.',
    description: '사찰 아래 가난한 마을 사람들의 비참한 삶을 그린 리얼리즘 단편. 부산 사하구의 절 아래 마을이 작품의 실제 배경이다. 부산 사하구 일대에서 요산 김정한의 문학적 현장을 만날 수 있다.',
    mood: ['아픔', '서민'],
    coords: { lat: 35.1042, lng: 128.9732 },
    district: '사하구'
  },

  // ═══ 제주 추가 ═══
  {
    id: 'lit-101',
    region: 'jeju',
    title: '바람 타는 섬',
    author: '현기영',
    year: 1989,
    genre: '소설',
    location: '제주 조천읍',
    excerpt: '바람은 섬의 주인이었다. 집도, 돌담도, 사람도 바람이 빚어놓은 것들이었다.',
    description: '제주 4·3 사건 이후 치유되지 않은 섬의 상처를 바람의 이미지로 그린 소설. 제주 조천 일대가 작품의 배경이다. 조천읍에서 소설 속 제주의 비바람을 느낄 수 있다.',
    mood: ['아픔', '치유'],
    coords: { lat: 33.5260, lng: 126.6350 },
    district: '조천읍'
  },

  // ═══ 서울 추가 ═══
  {
    id: 'lit-102',
    region: 'seoul',
    title: '성북동 비둘기',
    author: '김광섭',
    year: 1969,
    genre: '시',
    location: '서울 성북동',
    excerpt: '성북동 산에 번지가 새로 생기면서\n본래 살던 성북동 비둘기만이 번지가 없어졌다.\n하늘로 날아 산으로 올라가 돌과 나무뿐인\n산 1번지 채석장에 살어도 보지만',
    description: '도시 개발에 밀려나는 비둘기를 통해 서울 근대화의 그늘을 노래한 시. 1960년대 성북동의 급격한 변화가 시의 배경이다. 성북동 일대에서 시 속 풍경의 변화를 느낄 수 있다.',
    mood: ['서민', '성찰'],
    coords: { lat: 37.5950, lng: 126.9948 },
    district: '성북동'
  },
  {
    id: 'lit-103',
    region: 'seoul',
    title: '만세전',
    author: '염상섭',
    year: 1924,
    genre: '소설',
    location: '서울 남대문역 일대',
    excerpt: '나는 현해탄을 건너왔다. 고국의 땅을 밟는 발바닥에서부터 눈물겨운 감동이 솟아올랐다.',
    description: '3·1운동 직전 도쿄에서 경성으로 돌아오는 지식인의 눈에 비친 식민지 조선의 비참한 현실을 그린 소설. 남대문역에서 서울 거리까지 주인공의 동선이 작품의 축이다. 서울역 일대에서 소설 속 경성의 흔적을 찾을 수 있다.',
    mood: ['각성', '비판'],
    coords: { lat: 37.5532, lng: 126.9726 },
    district: '중구'
  },
  {
    id: 'lit-104',
    region: 'seoul',
    title: '빈처',
    author: '현진건',
    year: 1921,
    genre: '소설',
    location: '서울 종로',
    excerpt: '그의 아내는 새벽부터 일어나서 무얼 만지고 있었다.',
    description: '식민지 지식인의 가난과 아내의 헌신을 사실주의적으로 그린 단편. 종로 일대 셋방이 소설의 공간적 배경이다.',
    mood: ['빈곤', '사실'],
    coords: { lat: 37.5709, lng: 126.9997 },
    district: '종로'
  },
  {
    id: 'lit-105',
    region: 'seoul',
    title: '봉별기',
    author: '이상',
    year: 1936,
    genre: '소설',
    location: '서울 종로 청진동',
    excerpt: '정희, 나는 참말 네가 좋은 것이 아니라 나는 참말 나를 좋은 것이다.',
    description: '기생 금홍과의 사랑과 이별을 자전적으로 기록한 이상의 수필체 소설. 종로 청진동 일대의 유흥가가 배경이다.',
    mood: ['사랑', '고독'],
    coords: { lat: 37.5707, lng: 126.9814 },
    district: '종로'
  },

  // ═══ 강원 추가 ═══
  {
    id: 'lit-106',
    region: 'chuncheon',
    title: '금 따는 콩밭',
    author: '김유정',
    year: 1935,
    genre: '소설',
    location: '춘천 실레마을',
    excerpt: '영식이는 눈이 째지게 콩밭을 살피고 있었다.',
    description: '가난한 농촌 총각의 순박한 사랑을 그린 김유정의 해학적 단편. 춘천 실레마을의 콩밭과 산골이 배경이다. 김유정문학촌에서 작가의 다양한 단편 세계를 만날 수 있다.',
    mood: ['해학', '사랑'],
    coords: { lat: 37.8190, lng: 127.7190 },
    district: '실레마을'
  },
  {
    id: 'lit-107',
    region: 'gangneung',
    title: '홍길동전',
    author: '허균',
    year: 1612,
    genre: '소설',
    location: '강릉 초당동 허균허난설헌기념공원',
    excerpt: '화설 조선국 세종조에 한 재상이 있으니 성은 홍이요 이름은 아무개라.',
    description: '적서 차별에 맞선 홍길동의 활약을 그린 한국 최초의 한글 소설. 강릉 초당동에서 태어난 허균의 파격적 사상이 작품에 담겨 있다. 강릉 초당동에 허균허난설헌기념공원이 있다.',
    mood: ['저항', '이상'],
    coords: { lat: 37.7780, lng: 128.9050 },
    district: '초당동'
  },

,
  // ═══ 보충 작품 ═══
  {
    id: 'lit-108',
    region: 'gyeongju',
    title: '역마',
    author: '김동리',
    year: 1948,
    genre: '소설',
    location: '경주 양북면',
    excerpt: '성기는 낯선 다방에서 옥화를 만났다. 그 여자의 눈빛 속에서 어머니의 눈빛을 보았다.',
    description: '역마살이 낀 핏줄의 운명적 방랑을 그린 김동리의 대표 단편. 경주의 시골 역마을이 작품의 배경이다. 경주 동리목월문학관에서 작가의 세계를 만날 수 있다.',
    mood: ['운명', '방랑'],
    coords: { lat: 35.8562, lng: 129.2247 },
    district: '동리목월문학관'
  },
  {
    id: 'lit-109',
    region: 'buyeo',
    title: '금강',
    author: '신동엽',
    year: 1967,
    genre: '시',
    location: '부여 금강변',
    excerpt: '금강아\n네 맑은 물빛 투명한 날\n아아, 백제여,\n피 묻은 기슭에 와서 운다',
    description: '동학에서 4·19까지 민중 혁명의 역사를 금강의 흐름에 실어 노래한 장편 서사시. 부여 금강변이 시의 핵심 무대이다. 부여 금강변에서 시인이 노래한 역사의 물줄기를 느낄 수 있다.',
    mood: ['역사', '저항'],
    coords: { lat: 36.2756, lng: 126.9098 },
    district: '신동엽문학관'
  },
  {
    id: 'lit-110',
    region: 'namwon',
    title: '흥보가',
    author: '판소리',
    year: 1700,
    genre: '소설',
    location: '남원 흥부마을',
    excerpt: '놀보가 흥보를 내어쫓으니 흥보 마누라 품에 어린것을 안고 울며 나서는디\n가련한지고 가련한지고 흥보 신세 가련한지고',
    description: '착한 동생 흥보와 욕심 많은 형 놀보의 이야기를 담은 판소리 다섯 마당의 하나. 남원 일대가 흥보가의 배경으로 전해진다. 남원에 판소리 관련 공연장과 체험시설이 있다.',
    mood: ['해학', '권선징악'],
    coords: { lat: 35.4164, lng: 127.3907 },
    district: '광한루'
  },
  {
    id: 'lit-111',
    region: 'busan',
    title: '갯마을',
    author: '오영수',
    year: 1953,
    genre: '소설',
    location: '부산 기장군 해안',
    excerpt: '해순이는 날이면 날마다 바다를 바라보며 서 있었다.',
    description: '전쟁미망인 해순이의 새 사랑과 어촌 공동체의 삶을 그린 단편. 동해안 어촌이 배경이며 부산 기장 해안의 정취가 묻어난다. 기장 해안 일대에서 소설 속 갯마을의 풍경을 만날 수 있다.',
    mood: ['사랑', '서정'],
    coords: { lat: 35.2436, lng: 129.2222 },
    district: '기장군'
  },
  {
    id: 'lit-112',
    region: 'hadong',
    title: '지리산',
    author: '이병주',
    year: 1972,
    genre: '소설',
    location: '하동 화개장터 일대',
    excerpt: '지리산은 그때도 푸르렀다. 사람이 사람을 죽이는 동안에도 산은 말이 없었다.',
    description: '해방 직후 지리산을 무대로 한 좌우 이념 갈등의 비극을 그린 대하소설. 하동 화개장터와 지리산 일대가 소설의 중심 무대이다. 하동 화개장터에서 소설 속 격동의 역사를 떠올릴 수 있다.',
    mood: ['역사', '비극'],
    coords: { lat: 35.1220, lng: 127.6410 },
    district: '화개면'
  },
  {
    id: 'lit-113',
    region: 'seoul',
    title: '비 오는 날',
    author: '손창섭',
    year: 1953,
    genre: '소설',
    location: '서울 해방촌',
    excerpt: '비가 왔다. 그것도 아주 몹시 왔다.',
    description: '한국전쟁 직후 서울 변두리에서 살아가는 상이군인 형제의 무기력한 일상을 그린 전후 문학의 대표작. 서울의 판잣집이 무대이다.',
    mood: ['무기력', '전쟁'],
    coords: { lat: 37.5430, lng: 126.9870 },
    district: '용산구'
  },
  {
    id: 'lit-114',
    region: 'seoul',
    title: '한중록',
    author: '혜경궁 홍씨',
    year: 1805,
    genre: '소설',
    location: '서울 창경궁',
    excerpt: '내 신세 생각하고 우리 경모궁 일을 생각하면 천만 가지 억울한 일이 가슴에 쌓여 있으니',
    description: '사도세자의 죽음을 아내인 혜경궁 홍씨가 기록한 궁중 회고록. 사도세자가 뒤주에 갇힌 창경궁이 비극의 현장이다. 창경궁에서 역사의 아픔을 느낄 수 있다.',
    mood: ['비극', '역사'],
    coords: { lat: 37.5789, lng: 126.9944 },
    district: '종로'
  },
  {
    id: 'lit-115',
    region: 'seoul',
    title: '엄마를 부탁해',
    author: '신경숙',
    year: 2008,
    genre: '소설',
    location: '서울역',
    excerpt: '일주일 전이었다. 너의 엄마가 서울역에서 사라졌다.',
    description: '서울역에서 사라진 어머니를 찾는 과정에서 가족의 의미를 돌아보게 되는 소설. 서울역이 상실과 기억의 출발점이다.',
    mood: ['가족', '그리움'],
    coords: { lat: 37.5532, lng: 126.9726 },
    district: '중구'
  },
  {
    id: 'lit-116',
    region: 'jeonnam',
    title: '심청전',
    author: '판소리',
    year: 1700,
    genre: '소설',
    location: '곡성 심청마을',
    excerpt: '심청이 인당수에 빠지는 날이야.\n아버지 눈 밝히기 위하야 모진 목숨 버리거늘\n아이고 아버지, 아이고 아버지.',
    description: '맹인 아버지의 눈을 뜨게 하려고 인당수에 몸을 던진 효녀 심청의 이야기. 전남 곡성이 심청의 고향으로 전해져 심청축제가 열린다. 곡성에 심청마을과 심청공원이 조성되어 있다.',
    mood: ['효', '감동'],
    coords: { lat: 35.2819, lng: 127.2923 },
    district: '곡성읍'
  },
  {
    id: 'lit-117',
    region: 'gwangju',
    title: '상한 영혼을 위하여',
    author: '고정희',
    year: 1983,
    genre: '시',
    location: '광주 망월동 묘역',
    excerpt: '바람이 분다\n살아 있는 것들은 다 흔들린다\n살아 있으므로 흔들리는 것이다',
    description: '5·18 이후 상한 영혼들의 치유와 연대를 노래한 민중 시인 고정희의 대표시. 광주 망월동 묘역의 아픔이 시의 바탕이다. 광주 5·18 국립묘지에서 시의 현장을 만날 수 있다.',
    mood: ['치유', '연대'],
    coords: { lat: 35.1667, lng: 126.8667 },
    district: '북구'
  },
  {
    id: 'lit-118',
    region: 'tongyeong',
    title: '칼의 노래',
    author: '김훈',
    year: 2001,
    genre: '소설',
    location: '통영 한산도 제승당',
    excerpt: '버려진 섬마다 꽃이 피고 있었다.',
    description: '이순신 장군의 내면을 1인칭으로 그려낸 역사소설. 한산대첩의 현장인 통영 한산도가 소설의 핵심 무대이다. 한산도 제승당에서 소설 속 장군의 고뇌를 떠올릴 수 있다.',
    mood: ['비장', '고독'],
    coords: { lat: 34.7640, lng: 128.5040 },
    district: '한산도'
  },
  {
    id: 'lit-119',
    region: 'gangwon',
    title: '삼포 가는 길',
    author: '황석영',
    year: 1973,
    genre: '소설',
    location: '삼척 삼포해변',
    excerpt: '눈은 그치지 않고 내렸다. 정씨와 영달이는 밤새 길을 걸었다.',
    description: '산업화에 고향을 잃은 떠돌이들의 방랑을 그린 단편. 강원도 삼포라는 작은 어촌이 돌아갈 수 없는 고향의 상징이다. 삼척 해안에서 소설 속 삼포의 정취를 느낄 수 있다.',
    mood: ['방랑', '그리움'],
    coords: { lat: 37.2350, lng: 129.2240 },
    district: '삼척시'
  },
  {
    id: 'lit-120',
    region: 'jeonbuk',
    title: '장마',
    author: '윤흥길',
    year: 1973,
    genre: '소설',
    location: '전주 일대',
    excerpt: '그해 여름 장마는 오래, 아주 오래 계속되었다.',
    description: '6·25 전쟁이 한 가족에 남긴 이념 갈등을 어린이의 시선으로 그린 분단 문학의 수작. 전북 시골마을의 장마철이 배경이다.',
    mood: ['분단', '가족'],
    coords: { lat: 35.8242, lng: 127.1480 },
    district: '전주시'
  },
  {
    id: 'lit-121',
    region: 'gyeongbuk',
    title: '등신불',
    author: '김동리',
    year: 1961,
    genre: '소설',
    location: '영주 부석사',
    excerpt: '중 만적은 불 앞에 꿇어 앉아서 명상에 잠겼다.',
    description: '자기 몸에 불을 붙여 부처가 되려 한 승려의 극한적 구도를 그린 소설. 경북 산사가 배경이며 부석사의 비장한 분위기가 느껴진다. 영주 부석사에서 소설의 종교적 배경을 체험할 수 있다.',
    mood: ['성찰', '비장'],
    coords: { lat: 36.9940, lng: 128.6788 },
    district: '부석면'
  },
  {
    id: 'lit-122',
    region: 'chungnam',
    title: '고향',
    author: '이기영',
    year: 1933,
    genre: '소설',
    location: '아산 배방읍',
    excerpt: '김희준은 십 년 만에 고향으로 돌아왔다. 그러나 고향은 그가 떠나올 때의 고향이 아니었다.',
    description: '일제강점기 농촌의 피폐한 현실과 농민 운동을 그린 카프 문학의 대표작. 이기영의 고향인 아산 배방읍 일대가 작품의 모티프다.',
    mood: ['저항', '서민'],
    coords: { lat: 36.7800, lng: 127.0040 },
    district: '배방읍'
  },
  {
    id: 'lit-123',
    region: 'jeonbuk',
    title: '아리랑',
    author: '조정래',
    year: 1994,
    genre: '소설',
    location: '김제 만경벌',
    excerpt: '아리랑 아리랑 아라리요, 아리랑 고개를 넘어간다.',
    description: '일제강점기 전북 만경벌을 중심으로 한 민족 수난사를 그린 대하소설. 김제 만경평야가 소설 속 농민 항쟁의 핵심 무대이다. 김제 만경읍에서 소설의 배경이 된 너른 들판을 만날 수 있다.',
    mood: ['역사', '저항'],
    coords: { lat: 35.7700, lng: 126.8800 },
    district: '만경읍'
  },
  {
    id: 'lit-124',
    region: 'jeonnam',
    title: '자산어보',
    author: '정약전',
    year: 1814,
    genre: '소설',
    location: '신안 흑산도',
    excerpt: '이 바다에 사는 물고기를 기록하노라. 이름도 모양도 각각 달라 그 쓰임이 다하지 못하니.',
    description: '유배된 정약전이 흑산도 바다의 해양생물을 기록한 어류 백과. 흑산도 어민들과 교류하며 관찰한 결과물이다. 신안 흑산도에 정약전유적지와 자산어보 관련 전시관이 있다.',
    mood: ['탐구', '자연'],
    coords: { lat: 34.6833, lng: 125.4333 },
    district: '흑산도'
  },
  {
    id: 'lit-125',
    region: 'seoul',
    title: '와사등',
    author: '김광균',
    year: 1939,
    genre: '시',
    location: '서울 종로',
    excerpt: '차단된 골목의 아스팔트 우에\n인적이 끊어진 어느 밤\n와사등이 나비처럼 날아 온다',
    description: '가스등 불빛을 나비에 비유한 모더니즘 시의 대표작. 1930년대 경성 야간 거리의 감각적 인상이 담겨 있다.',
    mood: ['도시', '감각'],
    coords: { lat: 37.5709, lng: 126.9997 },
    district: '종로'
  },
  {
    id: 'lit-126',
    region: 'seoul',
    title: '불꽃',
    author: '선우휘',
    year: 1957,
    genre: '소설',
    location: '서울 종로',
    excerpt: '고현은 전쟁이 끝나자 서울로 돌아왔다. 종로 네거리는 여전했다.',
    description: '한국전쟁의 트라우마를 안고 사회에 복귀한 지식인의 방황을 그린 전후 문학의 수작. 전쟁 후 서울 종로 일대가 배경이다.',
    mood: ['전쟁', '방황'],
    coords: { lat: 37.5709, lng: 126.9997 },
    district: '종로'
  },
  {
    id: 'lit-127',
    region: 'mokpo',
    title: '사랑손님과 어머니',
    author: '주요섭',
    year: 1935,
    genre: '소설',
    location: '목포 목포문학관',
    excerpt: '어머니가 사랑방에 든 손님한테 달걀을 가져다주라고 하셨다.',
    description: '미망인 어머니와 사랑방 손님 사이의 감정을 어린 딸의 시선으로 그린 단편. 목포에서 활동한 주요섭의 세밀한 심리 묘사가 돋보인다. 목포문학관에서 근대 문학의 흔적을 찾을 수 있다.',
    mood: ['사랑', '감성'],
    coords: { lat: 34.7928, lng: 126.4169 },
    district: '목포문학관'
  },
  {
    id: 'lit-128',
    region: 'ulsan',
    title: '해',
    author: '서덕출',
    year: 1929,
    genre: '시',
    location: '울산 간절곶',
    excerpt: '바다는 하늘 아래 물감 풀어 놓은 듯\n새파란 물감으로 파도가 일어\n해야 해야 나오너라',
    description: '어린이의 순수한 감각으로 바다에서 떠오르는 해를 노래한 아동문학의 선구적 작품. 울산 출신 서덕출이 동해의 일출을 노래했다. 울산 간절곶에서 한반도 가장 빠른 일출을 볼 수 있다.',
    mood: ['희망', '서정'],
    coords: { lat: 35.3550, lng: 129.3592 },
    district: '간절곶'
  },
  {
    id: 'lit-129',
    region: 'gyeongnam',
    title: '별',
    author: '황순원',
    year: 1940,
    genre: '소설',
    location: '합천 해인사 일대',
    excerpt: '할아버지의 산소에는 별이 많았다. 별이 많은 밤이면 아버지가 그리워졌다.',
    description: '소년의 눈으로 본 가족과 자연의 서정을 그린 짧은 단편. 경남 산골의 밤하늘이 배경이다.',
    mood: ['서정', '그리움'],
    coords: { lat: 35.8020, lng: 128.1000 },
    district: '합천읍'
  },
  {
    id: 'lit-130',
    region: 'daegu',
    title: '마당 깊은 집',
    author: '김원일',
    year: 1988,
    genre: '소설',
    location: '대구 중구',
    excerpt: '우리 집은 마당이 깊었다. 대문에서 안마당까지 한참을 걸어 들어가야 했다.',
    description: '6·25 전쟁 직후 대구 피난민 마을을 배경으로 한 성장소설. 대구의 마당 깊은 대가족 집에 모여든 피난민들의 삶과 상처를 어린아이의 눈으로 그렸다. 대구 근대골목에서 전후 피난민 생활의 흔적을 만날 수 있다.',
    mood: ['성장', '전쟁'],
    coords: { lat: 35.8714, lng: 128.6014 },
    district: '중구'
  },
  {
    id: 'lit-131',
    region: 'jeju',
    title: '지상에 숟가락 하나',
    author: '현길언',
    year: 1983,
    genre: '소설',
    location: '제주 서귀포',
    excerpt: '어머니는 밭으로 나가셨다. 바람이 거칠었다.',
    description: '제주 농촌의 가난한 가족이 삶을 지탱해가는 이야기를 통해 존재의 의미를 묻는 소설. 서귀포 일대의 돌담 밭과 바람이 작품에 스며 있다.',
    mood: ['삶', '성찰'],
    coords: { lat: 33.2531, lng: 126.5595 },
    district: '서귀포'
  },

,
  {
    id: 'lit-132',
    region: 'sokcho',
    title: '그 여자네 집',
    author: '박완서',
    year: 2004,
    genre: '소설',
    location: '속초 설악산 일대',
    excerpt: '눈이 오면 속초가 좋다. 설악이 하얘지면 세상일이 다 하얗게 묻혀 버리는 것 같았다.',
    description: '속초를 배경으로 한 여성의 삶과 가족사를 그린 장편소설. 설악산과 동해바다가 어우러진 속초의 사계절이 작품에 스며 있다.',
    mood: ['가족', '서정'],
    coords: { lat: 38.2070, lng: 128.5918 },
    district: '설악동'
  },
,
  // ═══ 에이전트 검증 작품 추가 ═══

  // 경주
  {
    id: 'lit-133',
    region: 'gyeongju',
    title: '윤사월',
    author: '박목월',
    year: 1946,
    genre: '시',
    location: '경주 동리목월문학관',
    excerpt: '송화 가루 날리는\n외딴 봉우리\n윤사월 해 길다\n꾀꼬리 울면',
    description: '외딴 산골의 봄날 풍경과 눈먼 처녀의 애틋한 그리움을 노래한 민요풍 서정시. 경주에서 태어난 박목월의 초기시 세계를 대표하는 작품이다. 경주 토함산 자락에 동리목월문학관이 있다.',
    mood: ['서정', '그리움'],
    coords: { lat: 35.7850, lng: 129.3340 },
    district: '동리목월문학관'
  },

  // 안동
  {
    id: 'lit-134',
    region: 'andong',
    title: '강아지똥',
    author: '권정생',
    year: 1969,
    genre: '소설',
    location: '안동 일직면 권정생동화나라',
    excerpt: '돌이네 흰둥이가 누고 간 똥입니다.',
    description: '버림받은 강아지똥이 민들레꽃의 거름이 되어 새 생명을 피워내는 동화. 안동 일직면 교회 문간방에서 살던 권정생이 가장 낮은 곳의 아름다움을 이야기했다. 안동 일직면에 권정생동화나라가 있다.',
    mood: ['서정', '성찰'],
    coords: { lat: 36.4730, lng: 128.7190 },
    district: '일직면'
  },

  // 영양
  {
    id: 'lit-135',
    region: 'yeongyang',
    title: '낙화',
    author: '조지훈',
    year: 1946,
    genre: '시',
    location: '영양 주실마을 지훈문학관',
    excerpt: '꽃이 지기로서니\n바람을 탓하랴\n주렴 밖에 성긴 별이\n하나둘 스러지고',
    description: '지는 꽃 앞에서 삶의 무상함을 관조한 청록파의 대표 서정시. 영양 주실마을에서 유년을 보낸 조지훈의 전통적 미의식이 녹아 있다. 영양 일월면 주실마을에 지훈문학관이 있다.',
    mood: ['서정', '성찰'],
    coords: { lat: 36.6720, lng: 129.1126 },
    district: '주실마을'
  },

  // 담양
  {
    id: 'lit-136',
    region: 'damyang',
    title: '면앙정가',
    author: '송순',
    year: 1533,
    genre: '시',
    location: '담양 면앙정',
    excerpt: '무등산 한 줄기 뫼이 동쪽으로 뻗어 있어\n멀리 떼쳐 와 제월봉이 되었거늘\n무변대야에 무삼 짐작 하노라',
    description: '호남 가사문학의 원류로 담양 제월봉 아래 면앙정 주변의 산수를 사계절로 노래한 작품. 정철의 성산별곡에 직접 영향을 준 가사문학의 선구작이다. 담양 봉산면에 면앙정이 전라남도 기념물로 보존되어 있다.',
    mood: ['서정', '자연'],
    coords: { lat: 35.3456, lng: 126.9794 },
    district: '봉산면'
  },

  // 목포
  {
    id: 'lit-137',
    region: 'mokpo',
    title: '이영녀',
    author: '김우진',
    year: 1925,
    genre: '소설',
    location: '목포 유달산 일대',
    excerpt: '유달산 밑의 사창가가 보이는 곳.\n판자를 이어 만든 좁은 오두막이 비뚤어져 있다.',
    description: '1920년대 목포 유달산 아래 사창가를 무대로 빈민의 삶을 자연주의 수법으로 그린 한국 근대 희곡의 선구작. 김우진이 살던 목포 서산동 일대가 작품의 실제 배경이다. 목포문학관에 김우진의 친필 원고가 국가등록문화유산으로 보존되어 있다.',
    mood: ['아픔', '사실'],
    coords: { lat: 34.7893, lng: 126.3855 },
    district: '유달산'
  },

  // 전남 (장흥)
  {
    id: 'lit-138',
    region: 'jeonnam',
    title: '목선',
    author: '한승원',
    year: 1968,
    genre: '소설',
    location: '장흥 천관산 일대',
    excerpt: '먼 바다에는 한가로운 잔물결의 이랑들이 햇빛을 받아\n금빛 고깃비늘처럼 반짝거리고 있었다.',
    description: '남도 바닷가 사람들의 원초적 삶과 욕망을 거친 문체로 그린 한승원의 등단작. 장흥 앞바다와 천관산이 작품의 근원적 배경이다. 장흥 대덕읍에 천관문학관이 있으며 한승원과 한강 부녀의 문학 세계를 만날 수 있다.',
    mood: ['서정', '비극'],
    coords: { lat: 34.6821, lng: 126.9073 },
    district: '대덕읍'
  },

  // 강진
  {
    id: 'lit-139',
    region: 'gangjin',
    title: '끝없는 강물이 흐르네',
    author: '김영랑',
    year: 1930,
    genre: '시',
    location: '강진 영랑생가',
    excerpt: '내 마음의 어딘 듯 한편에\n끝없는 강물이 흐르네\n돋쳐 오르는 아침 날빛이\n빤질한 은결을 돋우네',
    description: '마음속 깊은 곳에 흐르는 순수한 감정을 강물의 이미지로 노래한 시. 시문학 창간호에 발표된 이 시는 강진의 맑은 물줄기에서 영감을 받았다. 강진읍 영랑생가 인근에 시비가 세워져 있다.',
    mood: ['서정', '순수'],
    coords: { lat: 34.6418, lng: 126.7678 },
    district: '강진읍'
  },

  // 광주
  {
    id: 'lit-140',
    region: 'gwangju',
    title: '아아 광주여 우리나라의 십자가여',
    author: '김준태',
    year: 1980,
    genre: '시',
    location: '광주 동구 광주문학관',
    excerpt: '아아 광주여 무등산이여\n죽음과 죽음 사이에\n피눈물을 흘리는\n우리들의 영원한 청춘의 도시여',
    description: '5·18 민주화운동을 문학으로 증언한 최초의 작품으로 1980년 6월 전남매일신문에 발표된 장시. 무등산과 광주 시내 전역이 시의 배경이다. 광주 동구에 광주문학관이 있다.',
    mood: ['아픔', '저항'],
    coords: { lat: 35.1540, lng: 126.9230 },
    district: '동구'
  },

  // 남해
  {
    id: 'lit-141',
    region: 'namhae',
    title: '사씨남정기',
    author: '김만중',
    year: 1692,
    genre: '소설',
    location: '남해 남해읍 남해유배문학관',
    excerpt: '유 한림이 육례를 갖추어 사 소저를 맞으니\n위의 성대하고 예도 아름다워\n당시 사람들이 부러워하지 않는 이 없더라.',
    description: '어진 아내 사씨가 악한 첩 교씨의 모함으로 쫓겨났다가 복권되는 권선징악 구조의 한글 소설. 김만중이 남해 유배 중에 숙종의 인현왕후 폐위를 비판하며 집필했다. 남해읍에 남해유배문학관이 있다.',
    mood: ['아픔', '성찰'],
    coords: { lat: 34.8365, lng: 127.8923 },
    district: '남해읍'
  },

  // 울산
  {
    id: 'lit-142',
    region: 'ulsan',
    title: '봄편지',
    author: '서덕출',
    year: 1926,
    genre: '시',
    location: '울산 중구 태화동',
    excerpt: '연못가에 새로 핀 버들잎을 따서요\n우표 한 장 붙여서 강남으로 보내면\n작년에 간 제비가 푸른 편지 보고요\n조선 봄이 그리워 다시 찾아 옵니다.',
    description: '버들잎 편지를 강남의 제비에게 보내 봄소식을 전한다는 동시로, 윤극영이 곡을 붙여 대표적 한국 동요가 되었다. 울산 태화강 인근에서 태어난 서덕출이 열아홉에 발표한 작품이다. 울산에서 매년 서덕출 창작동요제가 열린다.',
    mood: ['서정', '희망'],
    coords: { lat: 35.5553, lng: 129.3140 },
    district: '태화동'
  },

  // 통영
  {
    id: 'lit-143',
    region: 'tongyeong',
    title: '행복',
    author: '유치환',
    year: 1947,
    genre: '시',
    location: '통영 중앙동 우체국',
    excerpt: '사랑하는 것은\n사랑을 받느니보다 행복하나니라.\n오늘도 나는\n에메랄드빛 하늘이 환히 내다뵈는\n우체국 창문 앞에 와서\n너에게 편지를 쓴다.',
    description: '사랑하는 이에게 편지를 쓰며 사랑 그 자체의 행복을 노래한 서정시. 시에 등장하는 우체국은 통영 중앙동우체국이며 에메랄드빛 하늘은 통영 앞바다에 비친 하늘이다. 통영중앙동우체국 앞에 시비와 빨간 우체통이 놓여 있다.',
    mood: ['사랑', '서정'],
    coords: { lat: 34.8480, lng: 128.4320 },
    district: '중앙동'
  },

  // 부산
  {
    id: 'lit-144',
    region: 'busan',
    title: '밀다원 시대',
    author: '김동리',
    year: 1955,
    genre: '소설',
    location: '부산 중구 광복동',
    excerpt: '밀다원은 광복동 로터리에서 시청 쪽으로 조금 내려가서 있는 2층 다방이었다.',
    description: '한국전쟁 당시 부산으로 피란 온 문인들의 궁핍한 일상과 예술혼을 그린 단편소설. 광복동 일대의 다방 밀다원이 피란 문인들의 사랑방이었다. 중구 40계단 문화관광테마거리에서 피란 시절의 흔적을 만날 수 있다.',
    mood: ['회상', '고독'],
    coords: { lat: 35.0987, lng: 129.0312 },
    district: '중구'
  },
  {
    id: 'lit-145',
    region: 'busan',
    title: '탈향',
    author: '이호철',
    year: 1955,
    genre: '소설',
    location: '부산 중구 부산역 부두 일대',
    excerpt: '무엇인가 못 견디게 그리운 것처럼 애탔다.\n그러나 누가 알랴! 지금 내 마음 밑속에서\n일어나는 돌개바람 같은 것을……',
    description: '한국전쟁 중 월남한 실향민 청년들의 부산 피란 생활과 정체성의 갈등을 그린 소설. 부산역과 부두 근처에서 화차에 숨어 잠자며 하역 일을 하는 장면이 배경이다. 초량 이바구길에서 피란민의 삶을 되짚을 수 있다.',
    mood: ['그리움', '방황'],
    coords: { lat: 35.1152, lng: 129.0403 },
    district: '중구'
  },

  // 제주
  {
    id: 'lit-146',
    region: 'jeju',
    title: '작별하지 않는다',
    author: '한강',
    year: 2021,
    genre: '소설',
    location: '제주 제주시 봉개동 일대',
    excerpt: '성근 눈이 내리고 있었다.\n내가 서 있는 벌판의 한쪽 끝은 야트막한 산으로 이어져 있었는데\n등성이에서부터 이편 아래쪽까지 수천 그루의 검은 통나무들이 심겨 있었다.',
    description: '제주 4·3 사건의 기억과 애도를 눈의 이미지로 형상화한 장편소설. 제주 중산간 마을의 학살 현장이 이야기의 중심 공간이다. 제주 4·3 평화공원에서 작품이 다룬 역사를 기릴 수 있다.',
    mood: ['아픔', '성찰'],
    coords: { lat: 33.4273, lng: 126.6060 },
    district: '봉개동'
  },
  {
    id: 'lit-147',
    region: 'jeju',
    title: '한라산',
    author: '이산하',
    year: 1987,
    genre: '시',
    location: '제주 한라산',
    excerpt: '오늘도 잠들지 않는 남도 한라산\n그 아름다운 제주도의 신혼여행지들은 모두\n우리가 묵념해야 할 학살의 장소이다.',
    description: '제주 4·3 사건의 참상을 정면으로 고발한 장편서사시. 한라산 자락의 마을들이 겪은 학살의 역사를 증언한다. 발표 당시 필화 사건으로 시인이 구속되었을 만큼 금기에 도전한 작품이다.',
    mood: ['저항', '아픔'],
    coords: { lat: 33.3617, lng: 126.5292 },
    district: '한라산'
  },
  {
    id: 'lit-148',
    region: 'jeju',
    title: '그리운 바다 성산포',
    author: '이생진',
    year: 1978,
    genre: '시',
    location: '제주 서귀포시 성산포',
    excerpt: '성산포에서는 사람은 슬픔을 만들고\n바다는 그 슬픔을 삼킨다.\n성산포에서는 사람이 슬픔을 노래하고\n바다는 그 노래를 듣는다.',
    description: '성산포 바다의 풍경과 인간의 고독을 겹쳐 노래한 연작시. 성산일출봉이 보이는 포구와 바다가 시의 무대이다. 성산포 해안가에 이생진 시비공원이 조성되어 있다.',
    mood: ['그리움', '고독'],
    coords: { lat: 33.4580, lng: 126.9425 },
    district: '성산읍'
  },
  {
    id: 'lit-149',
    region: 'jeju',
    title: '까마귀의 죽음',
    author: '김석범',
    year: 1957,
    genre: '소설',
    location: '제주 제주시 일대',
    excerpt: '그들은 까마귀 같은 검은 군복을 입은 자들이\n제주의 하늘 아래 횡행하는 것을 보았다.',
    description: '재일조선인 작가가 4·3 사건을 세상에 처음 알린 소설로 대작 화산도의 모태가 된 작품. 미군정 하 제주에서 비밀 당원으로 활동하는 청년의 저항을 그렸다. 제주 4·3 평화기념관에서 이 시대의 역사를 만날 수 있다.',
    mood: ['저항', '아픔'],
    coords: { lat: 33.5100, lng: 126.5219 },
    district: '제주시'
  },

];
